### ISSUE TITLE
Missing Harp Timestamps

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#10]
@bruno-f-cruz @jsiegle 

Hey Bruno, 

I recently found that sometimes Harp timestamps are missing. The frequency of missing is approximately once every 200 trials. 

Currently, I only found the missing was happening on Start and GoCue (related workflow is shown below). It's not the problem of OSC message as timestamps that are not associated with Harp behavior board output are sending correctly. I also checked the BehaviorEvents bin file, and the timestamp was also missing in the bin file. 

Do you have any ideas that this has something to do with the instability of the Harp board or the code in the workflow?

![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/86a3ddd4-47eb-42ae-ad5c-fccec471ee4a)
![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/c6b5e80e-bdd3-4cbd-8c40-b269770b3daa)
![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/5eb9f926-ea6f-4f97-aa41-7570f1a28ace)

**Comment by bruno-f-cruz** [comment]
Did you update the firmware as we discussed last time? This is a known
fixed bug.

**Comment by XX-Yin** [comment]
Do you mean installation of a specific Bonsai package?

**Comment by bruno-f-cruz** [comment]
Nop, I mean the actual board firmware. [This is the latest version.](https://github.com/harp-tech/device.behavior/releases/tag/fw3.1-harp1.11)

**Comment by XX-Yin** [comment]
Thanks! No, I have not updated it. Will let you know if it works.

**Comment by XX-Yin** [comment]
> Nop, I mean the actual board firmware. [This is the latest version.](https://github.com/harp-tech/device.behavior/releases/tag/fw3.1-harp1.11)

Do we have a manual telling how to update the board firmware in Harp?

**Comment by bruno-f-cruz** [comment]
I think Josh might have written this down somewhere from one of the meetings. Anyway:

1. Add a device node and set the correct COM port
2. Before running the workflow, double-click the device node. This will open a new window dialog
3. Click Bootloader
4. Open... and target the firmware you downloaded
5. Click update

**Comment by XX-Yin** [comment]
Thanks! I will try this first.

**Comment by XX-Yin** [comment]
It seems that I successfully updated the board firmware. Will these updates be synchronized to dynamic foraging task git repo? Or we need to update it in each computer when we install the dynamic foraging workflow?

**Comment by bruno-f-cruz** [comment]
The firmware is specific to the harp behavior board in question. Each board has its own "firmware" running in its microcontroller. The host PC does not have save any persistent state of the board's firmware, if that is what you are asking. To make sure that every rig behaves the same you should update every single board to this firmware version. This process must only be done once per board, and can even be performed from the same computer if you so wish.

**Comment by XX-Yin** [comment]
That's clear to me now!

**Comment by XX-Yin** [comment]
Thanks Bruno! This issue was solved. I ran the task over 12 hours and over 6000 trials. It's still working normally.

**Comment by XX-Yin** [comment]
Solved!
