### ISSUE TITLE
Update Bias indicator

### ISSUE THREAD

**Issue by micahwoodard** [AllenNeuralDynamics/dynamic-foraging-task#1027]
In order to more accurately calculate bias, we need to: 
- change argument n_trial_back to 5 
- change cross validation argument cv to 5
- only input last 200 choice/reward history
- add bootstrap [confidence intervals](https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-models/blob/80361bf594fc99ba6d6558c35308550b0264e1a7/src/aind_dynamic_foraging_models/logistic_regression/model.py#L228) to graph

**Comment by micahwoodard** [comment]
@alexpiet would it break the post processing pipeline to rename  B_NewscalePositions to B_StagePositions and then make it a dictionary instead of a list? That way we could handle the newscale have x,y,z coords and aind having x, y0, y1, z coords

**Comment by alexpiet** [comment]
On one example session I computed the bias and varied "n_trials_back" between 3, 5, and 7. I then varied "window_size" between [50,100,150,200,250]

![example_bias_n_trials_back](https://github.com/user-attachments/assets/ba896be0-7538-450e-81a5-4c017cb0f104)
![example_bias_window_size_big](https://github.com/user-attachments/assets/e1638836-1be8-4d17-a1eb-e6bc0243958e)
![example_bias_window_size_small](https://github.com/user-attachments/assets/78f21258-1316-4098-8ebd-b7ed2e68ba84)

**Comment by JeremiahYCohen** [comment]
I have a weak preference for smaller window size (50 or 100) so that it's sensitive to local fluctuations in bias (but could be convinced otherwise).

**Comment by hanhou** [comment]
Could you also show some sessions with moderate and severe bias? I think the proper window size depends on how frequent we want to move the lickspout. See [doc here](https://alleninstitute.sharepoint.com/:w:/s/NeuralDynamics/EegXPhm7k1ZDo2Gv9pq2EVsB7eu3ervwSNFAs89Fl_myDg?e=1c18W4).

**Comment by alexpiet** [comment]
Here is the entire training history for a mouse

![behavior_739199_2024-09-30_09-17-08](https://github.com/user-attachments/assets/7663a725-4e31-410c-9467-93d30b316425)
![behavior_739199_2024-10-02_09-51-12](https://github.com/user-attachments/assets/8a197f5b-4a93-4255-9112-7d4074ade29b)
![behavior_739199_2024-10-03_09-18-53](https://github.com/user-attachments/assets/a858b1f0-cd89-441f-856a-0f67811cbbd6)
![behavior_739199_2024-10-04_09-14-04](https://github.com/user-attachments/assets/4540692f-1222-40ea-9f89-27002fab8c21)
![behavior_739199_2024-10-07_09-18-47](https://github.com/user-attachments/assets/f6454952-3061-4437-8ab1-037f178688b5)
![behavior_739199_2024-10-08_09-07-28](https://github.com/user-attachments/assets/3ecd1066-be75-43bf-8941-3ee8aea1e8d3)
![behavior_739199_2024-10-09_09-13-50](https://github.com/user-attachments/assets/50dcea9f-aad6-4f79-aaa2-5b24f3e17e26)
![behavior_739199_2024-10-14_09-51-46](https://github.com/user-attachments/assets/5dadff5d-d90d-45dc-8caf-d3395873f1f8)
![behavior_739199_2024-10-16_09-38-53](https://github.com/user-attachments/assets/997bea70-efbc-4de1-820b-9aff94ced6c5)
![behavior_739199_2024-10-17_09-11-30](https://github.com/user-attachments/assets/ee5ae206-5c31-4620-b608-4c2ea9822181)
![behavior_739199_2024-10-18_09-37-56](https://github.com/user-attachments/assets/2a79e995-1aaa-4f9f-a84f-c08692af7bfd)
![behavior_739199_2024-10-21_09-51-03](https://github.com/user-attachments/assets/d26b82c4-8948-45b6-8180-be51b5f137af)
![behavior_739199_2024-10-23_09-52-59](https://github.com/user-attachments/assets/abaa1410-ffa5-414f-9672-2ddb2cebcb53)
![behavior_739199_2024-10-24_09-22-13](https://github.com/user-attachments/assets/6bfc1f60-079f-4d83-8868-53ecf39170f1)
![behavior_739199_2024-10-25_09-48-52](https://github.com/user-attachments/assets/2cc2622d-ad85-444b-b3af-1ab054bca24a)
![behavior_739199_2024-10-30_09-40-20](https://github.com/user-attachments/assets/8de67d4c-5ef9-48a3-94cc-37e459194f07)
![behavior_739199_2024-10-31_09-14-42](https://github.com/user-attachments/assets/2874bc03-0415-4436-87a3-5e75c25d6056)
![behavior_739199_2024-11-01_10-13-22](https://github.com/user-attachments/assets/96d5d2ec-82bf-408c-9d09-402321c28002)
![behavior_739199_2024-11-04_09-57-39](https://github.com/user-attachments/assets/e909a7a1-8b26-4a75-b417-b378cb8cbd92)

**Comment by hanhou** [comment]
> Here is the entire training history for a mouse

I feel the blue one is the closest to my estimate of bias.

**Comment by alexpiet** [comment]
@micahwoodard based on discussion in the meeting after you left. Lets try out n_trials_back=5, compute_every=10, max_window=200.

**Comment by alexpiet** [comment]
@micahwoodard Can you also update the x-axis on the bias plot to show trial # rather than time

**Comment by micahwoodard** [comment]
> * You should use aind-dynamic-foraging-models >=0.11.2 (https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-models)

@alexpiet I think I pinned the main branch of aind-dynamic-foraging-models. Will that work as well?
