### ISSUE TITLE
Display window writes "No calibration for this laser identified!" when there is no laser

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#104]
It looks like OptogenticsDialog checks to see if `._Laser_1` has currentText == "NA", but it doesn't appear that field ever gets populated

@XX-Yin

**Comment by XX-Yin** [comment]
When it's NA, the "No calibration for this laser identified!" will also appear. We can modify it.

**Comment by alexpiet** [comment]
@XX-Yin 
- Where does the "NA" attribute get set?
- How should we modify the dialog to not display the warning?

I'm happy to implement if you point me in the right direction

**Comment by XX-Yin** [comment]
Just need to exclude the NA in line 219-273 in the Dialogs.py.

**Comment by alexpiet** [comment]
The issue here is that `Optogenetics.py` defaults Laser 1 to have status `Blue` rather than `NA`. This was intentional because that is the most common configuration when optogenetics is used. 

@XX-Yin and I discussed it and decided that it should default to `NA` because most sessions will not have optogenetics, and when they do they can then set the parameters. @XX-Yin said he will change the default and make a PR.

**Comment by alexpiet** [comment]
Closing this issue as resolved by #105
