### ISSUE TITLE
Update FIP schedule check to use "First FP Stage"

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#1045]
If the schedule shows:
FP		Axon	FINAL

Then don't send an alert for starting the session without FIP unless the mouse is on "FINAL"

**Comment by alexpiet** [comment]
Check for `TP_auto_train_stage` == 'Final'

**Comment by micahwoodard** [comment]
Might be an edge case, but what should we do if the training stage is undefined the gui? I defaulted it to still warn and log an error but can change

**Comment by ellahiltonvano** [comment]
I had made this issue that could help solve the above case @micahwoodard, but it may be more trouble than its worth (currently the stages should be mostly correct, but RAs sometimes forget to update each day) https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/686
