### ISSUE TITLE
Warning related to running out of space 

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#1099]
Previously, the color of the space bar would become red when the space exceeds 90% or less than 100Gb. Recently, the color was not changed.

**Comment by ellahiltonvano** [comment]
@micahwoodard was this intentional? The color used to be a purple when the above criteria were met, now its green the entire time

**Comment by ellahiltonvano** [comment]
@XX-Yin #947 is also an issue open that will alert users (color change would still be helpful as well)

**Comment by XX-Yin** [comment]
> @XX-Yin #947 is also an issue open that will alert users (color change would still be helpful as well)

Yes, an alert is helpful.

**Comment by micahwoodard** [comment]
@XX-Yin and @ellahiltonvano this was not intentional no. I can't even think of a recently solved issue that would have affected this. Maybe the warning widget? I'll assign myself this issue and investigate

**Comment by XX-Yin** [comment]
Thanks Micah!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ellahiltonvano** [comment]
@micahwoodard is this something that you could prioritize? It seems like space is filled up pretty quickly these days so want to make sure we are catching this before data is lost

**Comment by micahwoodard** [comment]
@ellahiltonvano yes I can try and get to it later this week
