### ISSUE TITLE
Mice did not add their water info to SLIMS

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#1111]
746346
754429

**Comment by alexpiet** [comment]
Can check mice here: http://eng-tools:8050/

**Comment by ellahiltonvano** [comment]
@alexpiet looks like it has uploaded, but was delayed? Or, it may have not uploaded for the same reason that the load function wasn't working - only a ~10min session on 12/2

![Image](https://github.com/user-attachments/assets/c6db5a8b-2464-483d-9920-5d517fa42a9c)

**Comment by jackieswapp** [comment]
Wooh, there it is!

@alexpiet  It also looks like the user name isn't coming with the weight/water data to SLIMS, is it possible to add that?

**Comment by alexpiet** [comment]
These are good questions for @micahwoodard

**Comment by alexpiet** [comment]
I would also follow up with SIPE about when their dashboard updates, since there shouldn't be any delay in the mice being in SLIMS

**Comment by ellahiltonvano** [comment]
@nathan-mars do you have an idea of when the SLIMS dashboard updates?

**Comment by nathan-mars** [comment]
Patrick may know if it's a waterlog question

**Comment by ellahiltonvano** [comment]
@alexpiet it sounds like all data is immediately moved to the database that the above tool pulls from. Patrick says that he doesn't think there is an auto update, but if a user submits the mouse ID again it should be read from the database with the most recent info.

**Comment by jessy-liao** [comment]
> > @alexpiet It also looks like the user name isn't coming with the weight/water data to SLIMS, is it possible to add that?
> 
> @jessy-liao sorry for the late response on this. When you say user name, are you referring to the [operator key](https://github.com/AllenNeuralDynamics/aind-slims-api/blob/4372b5dd4bd89f012bb9a46e0a46e06de050aa6b/src/aind_slims_api/models/waterlog_result.py#L54C5-L58C6) in the SLimsWaterlogResult? If so, would this be populated with the Slims username or the person who ran the session?

@micahwoodard User name on the Mouse Water Weight web-tool is pulled from "rslt_cf_waterlogOperator", the same operator key you linked to. Questions about populating the field would be for Patrick (I believe waterlog is doing the populating, and your app too).

**Comment by jessy-liao** [comment]
> @alexpiet it sounds like all data is immediately moved to the database that the above tool pulls from. Patrick says that he doesn't think there is an auto update, but if a user submits the mouse ID again it should be read from the database with the most recent info.

@ellahiltonvano Yes, the above tool just pulls from the SLIMS/LIMS database. If there were changes to the database you would have to refresh and query the mice again. I was the one who wrote this tool so if you noticed any issues or have feedback let me know.

**Comment by ellahiltonvano** [comment]
This seems to be working well now. I verified that you can see data in SLIMS right after saving a session in the GUI.
