### ISSUE TITLE
Upload manifest issues

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#1114]
It appears there are multiple issues related to data upload. This appears to only being happening on the production_testing branch
- Saved data is stored at `behavior_behavior_<mouse_id>_<date time>` instead of `behavior_<mouse_id>_<date time>`
- The behavior modality is not accurately being added to the upload manifest

**Comment by alexpiet** [comment]
I suspect the `behavior_behavior_` issue is something to do with https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/1003. @micahwoodard Can you take a look?

I suspect the behavior modality not being added is due to https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/1051 causing a breaking change. @XX-Yin Can you take a look?

**Comment by alexpiet** [comment]
To be explicit about the behavior modality: the upload manifest code checks for `Modality.BEHAVIOR in stream.stream_modalities`, yet in sessions generated by the testing branch, there is no `Modality.BEHAVIOR` in stream.stream_modalities.

@XX-Yin Is this intentional? If so, we need to modify the upload manifest code. If not, we need to fix how we make the session.json

**Comment by XX-Yin** [comment]
It's intentional to remove the behavior from the stream per Saskia's suggestion. This is one error I found.

**Comment by XX-Yin** [comment]
@alexpiet I will make PR to update the manifest code
