### ISSUE TITLE
Cannot install and run develop branch due to missing dependency

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/dynamic-foraging-task#1118]
It works on my computer. However, I found an issue in the develop branch, the `aind_behavior_services` package is not found. The package is not defined in the `pyproject.toml`

_Originally posted by @XX-Yin in https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/1115#issuecomment-2518287632_

**Comment by alexpiet** [comment]
Thats strange, since this PR added it: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/1003/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Comment by alexpiet** [comment]
And its in the production_testing branch. So some more recent PR must have removed it, which is troubling

https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/66edb6f236fce48d1c816fba8b3b07bf528611c9/pyproject.toml#L31

**Comment by galenlynch** [comment]
That is a very strange dependency range. Should it be 0.8?

**Comment by alexpiet** [comment]
I don't know. @micahwoodard added that dependency recently

**Comment by galenlynch** [comment]
Closed by #1119
