### ISSUE TITLE
Does `switch to main.bat` and the weekly upgrade also rebuild the environment?

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/dynamic-foraging-task#1121]
While testing #1115 I did not notice that the environment was rebuilt. Is the environment rebuilt each week during updates?

**Comment by alexpiet** [comment]
Yes. It calls this script/line: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/1a7c9d3d1aa10284caed44ba9b223c6bfbb8ff5f/src/update_scripts/update_from_github_to_main.bat#L26

**Comment by galenlynch** [comment]
What happens if dependencies are removed?

**Comment by alexpiet** [comment]
I'm not totally sure - presumably they are left installed in the conda environment. The pip install --upgrade won't remove them, and we don't delete and remake the conda environment.

**Comment by galenlynch** [comment]
Maybe this is attempting to fix a problem that doesn't currently exist, but you could get in a situation where old requirements limit the installation of specific versions of dependencies. A fresh install would end up with a different environment than an old install that has had weekly upgrades.

**Comment by alexpiet** [comment]
thats true, and something that could become a bigger problem as time goes on

**Comment by galenlynch** [comment]
OK I was just curious. Seems like we should address that when it's actually a problem.
