### ISSUE TITLE
weird bias figure

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#1172]
![image](https://github.com/user-attachments/assets/c5e48fcb-2fbc-43db-8755-265bf9194c40)

The bias looks weird. Any ideas? @micahwoodard

**Comment by micahwoodard** [comment]
Huh that does look weird. I will investigate tomorrow

**Comment by micahwoodard** [comment]
@XX-Yin what session was this?

**Comment by XX-Yin** [comment]
@micahwoodard It was this session \\allen\aind\scratch\ephys_rig_behavior_transfer\764769\behavior_764769_2024-12-12_16-05-00\behavior. 

It seems to be related to the discontinuity of fitting for initial trials (more noisy).

**Comment by XX-Yin** [comment]
Are you using the same smooth window for the average and the error shading?

**Comment by XX-Yin** [comment]
Another case
![image](https://github.com/user-attachments/assets/ef2963be-fd82-4f56-8b28-c455d435ef2b)

Is the data from the previous session cleared?

**Comment by micahwoodard** [comment]
> Another case ![image](https://github.com/user-attachments/assets/ef2963be-fd82-4f56-8b28-c455d435ef2b)
> 
> Is the data from the previous session cleared?

Yes should be. I'll take a look at this
