### ISSUE TITLE
Harp sound card GUI

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#12]
We ran into some issues with the Harp GUI when we tried to load a waveform to the sound card.

There is some information that can help narrow down the problem.
1) There is a warning when I click "Connection w/ device".
![bb45d0cf-c0e4-4e16-a0fb-3033aaa8f5ac](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/d5ac93da-3890-4034-aaf9-e106f6756917)

2) We can place the sound but can't load it. When we tried to load the waveform onto the card, a warning popped up.
![d466cd98-b7f7-4f48-a337-78f6358d8e64](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/2bd95876-2237-4d57-869d-2beb9d9f37be)

3) We plugged in both cables of the sound card. 

Hi @filcarv, @bruno-f-cruz and @jsiegle, do you have any ideas?

**Comment by alexpiet** [comment]
@XX-Yin Is this issue still active?

**Comment by XX-Yin** [comment]
I found it is not robust. Most of the time I get it correct, but occasionally I get errors.

**Comment by alexpiet** [comment]
Closing this issue as solved by #407
