### ISSUE TITLE
Remove hasNiDaq from settings files, enable Optogenetics by default

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#121]
- [ ] We need to include hasNidaq=0 
- [ ] Does this live in ForagingSettings.json, or Settings_box.csv?
- [ ] We need to document on the README that this setting exists

UPDATE: hasNidaq is outdated, and no longer needed. We can enable Optogenetics Node by default

**Comment by XX-Yin** [comment]
@alexpiet We no longer need the hasNidaq=0 setting. Issue [#120](https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/120) is related to the NIdaq driver. If we install the NIdaq driver, it will not cause the error even if we don't have NIdaq.

**Comment by XX-Yin** [comment]
I will clean the Bonsai code to delete this part.

**Comment by alexpiet** [comment]
So if we enable the Optogenetics Node by default in bonsai, then we don't need the hasNidaq setting, even for computers without a Nidaq?

**Comment by XX-Yin** [comment]
> So if we enable the Optogenetics Node by default in bonsai, then we don't need the hasNidaq setting, even for computers without a Nidaq? (Thats great if true!)

Yes. We can enable the Optogenetics node by default.

**Comment by alexpiet** [comment]
Great, can you make a PR that enables that?

**Comment by XX-Yin** [comment]
The optogenetics node has already been enabled in the previous PR. 

I created a PR to remove hasNiDaq from the bonsai workflow. https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/127
