### ISSUE TITLE
Need to document how to set the Teensy_COM, and what it is used for

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#124]
This is a setting in ForagingSettings.json, and I dont know what it is

**Comment by XX-Yin** [comment]
This is related to Kenta's photometry. @hagikent

**Comment by hagikent** [comment]
Teensy is a micro-computer controlling the photometry system. 
As it receives serial commands from the Foraging-GUI, we need to feed COM# to the GUI through ForagingSettings.
I will add description to the Wiki.

**Comment by alexpiet** [comment]
Thanks @hagikent, please include documentation on how to determine the COM#

**Comment by alexpiet** [comment]
Resolved with #123
