### ISSUE TITLE
Adopt AIND-Schemas for standardization of data

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#129]
- [x] rig
- [x] subject
- [ ] session

**Comment by alexpiet** [comment]
- rig jsons should be in repo
- SLIMS has database of instruments
-

**Comment by alexpiet** [comment]
#303 partially overlapping

**Comment by hanhou** [comment]
- https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/68
