### ISSUE TITLE
Handle the first session in auto training

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#146]
As we previously discussed, the with-session transition from stage 1.1 (tens of L-R-L-R alternating trials) to stage 1.2 (real foraging) should be handled locally in the GUI. This is one of the only two missing parts in our automated training system (https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/73).

Here I propose a more general way of doing this. Instead of hardcoding the L-R-L-R part and defining a transition rule to 1.2 for **_only the first session_**, we can in fact add a general `warm-up` option into the `task schema`, i.e., add following parameters to the GUI:
- `warmup_enabled: bool = False`: a switch to turn on/off the warm up section
- `warmup_block_length: int = 1`: the length of block during warm-up
- `warmup_reward_probs: list = [0, 1]`: the reward probs during warm-up
- `warmup_min_trials: int = 30`: the minimum length of warm-up
- `warmup_max_choice_ratio_bias: float = 0.1`: the maximum deviation from a `choice ratio` of 0.5 (no bias)
- `warmup_min_finish_ratio: float = 0.7`: the minimum of the `finished ratio` (finished trials / total trials)
- `warmup_trials_to_compute_ratios: int = 20`: the length of the sliding window by which we compute the two ratios

The warmup is always simple left-right alternating blocks with `warmup_block_length` and `warmup_reward_probs`, and we always use this simple criterion to end the warmup:

```
if (
number of warmup trials >= `warmup_min_trials`
and for recent `warmup_trials_to_compute_ratios` trials,
    finished ratio >= `warmup_min_finish_ratio`
    and 
    abs(proportion of choosing Right - 0.5) <= `warmup_max_choice_ratio_bias`
)
```

With this design, we could just turn `warmup_enabled` on for the first session to implement stage 1.1 -> stage 1.2. It also makes it possible if one would like to include a warm-up to not only the first session (presumably with larger warmup_block_length and lower warmup_reward_probs). Most importantly, everything is defined and tracked under the same task schema, and the first session is no longer special.

@XX-Yin @alexpiet what do you think? If this makes sense, Xinxin, could you implement this interface in the GUI?

**Comment by hanhou** [comment]
btw, we could implement the within-session automated lickport movement in the same way, which is the other one of the only two missing pieces.

**Comment by alexpiet** [comment]
The most general solution would allow people to let trial structure change throughout the session. 

For example, what if we want to start mice alternating L/R, but then slowly increase the number of trials on each side: L, R, LL, RR, LLL, RRR, ....

**Comment by hanhou** [comment]
> The most general solution would allow people to let trial structure change throughout the session.
> 
> For example, what if we want to start mice alternating L/R, but then slowly increase the number of trials on each side: L, R, LL, RR, LLL, RRR, ....

I think it boils down to the question of how slow is slow enough (like our discussion about gradual versus step-wise lickspout movement). Our experience is that, in general, increasing the block length on a session-by-session basis is smooth enough for their learning. I believe this is not the global optimum, but it does make our task and curriculum much simpler.

The reason we want to add LRLR to the first session is that this is when they learn the idea of "two tubes that deliver water" for the first time, which may be conceptually different than they progress in the foraging task later on. And from my experience, even in later sessions, having some fixed length L-R blocks with lower reward probabilities before the real foraging task may be helpful to fight against bias (rather than rolling back the whole session to a bias-fighting session). This is why I think making the solution slightly more general (but not too general) might be a good idea.

**Comment by XX-Yin** [comment]
I have some questions about this. It's best to talk in person.

**Comment by hanhou** [comment]
@XX-Yin Please let me know if you would have time to implement this.

**Comment by XX-Yin** [comment]
> @XX-Yin Please let me know if you would have time to implement this.

@hanhou Sure, I will try to implement this week (super busy recently).
