### ISSUE TITLE
Sync installation instructions on wiki and readme

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#154]
or remove one of the two. I move the instructions to the wiki for faster editing while I update all the 447 rigs

**Comment by hagikent** [comment]
I was thinking of this and already rearranged the wiki (in the `behavior-blog`) a bit.
It's also a bit frustrating that you need to go back and forth between `blog` and `foraging` when setting up PCs. Would you think it's ok to put all the installation instructions in the `blog` and then having a link to it in `foraging`? 

As the `blog` repo is (will be) private, it might be an issue when disseminating `dynamic-foraging-task` widely in the future...though. @alexpiet any thought?

**Comment by alexpiet** [comment]
I'm fine with whatever is easiest to use
