### ISSUE TITLE
Naming convention changes break "Tower" index logic

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#156]
Right now, when the settings are loaded, the tower is set by determining the index in the options of the GUI window for current box. The options are outdated now, so the tower index will never be set. 
- One option is to simply add the new boxes to the options in the tower index.
- alternative (my preference), we remove all logic and instances of "tower" since its only used to create folders for data saving.
- When we update the room again to use one box per computer, we can greatly simplify this logic, to just have the current_box setting in the setting files specify the full box "447-1-A"

**Comment by alexpiet** [comment]
Or, we need to rename this to "box", and add the new names to the default options in the GUI

**Comment by XX-Yin** [comment]
"When we update the room again to use one box per computer, we can greatly simplify this logic, to just have the current_box setting in the setting files specify the full box "447-1-A""

I like this one to just set the full name in the setting files.
