### ISSUE TITLE
Make workflow compatible with multiple rig configurations

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/dynamic-foraging-task#16]
Current dependencies include:

Osc Port
COM Port
 - Behavior
 - Sound
 - Sync

Camera (Optional)
 - Serial numbers

Nidaq
 - Dev Number

**Comment by alexpiet** [comment]
I'm closing this issue because all rig specific configurations are now in settings files, and a clean git pull will work without manual intervention.

**Comment by bruno-f-cruz** [comment]
I don't believe the nidaq is defined via the external file yet. At least the strategy I showed xin xin is not compatible without writing some custom csharp classes. If this is not required, feel free to keep this issue closed.

**Comment by XX-Yin** [comment]
> I don't believe the nidaq is defined via the external file yet. At least the strategy I showed @XX-Yin is not compatible without writing some custom csharp classes. If this is not required, feel free to keep this issue closed.

Hi Bruno, nidaq is not defined via an external file. Currently, all nidaqs have the same name "dev0", so we usually don't need to change it. But it would be great if we could preset it via an external file because in the future we might have multiple nidaqs.

**Comment by alexpiet** [comment]
@XX-Yin Can you make a new issue about a nidaq external file, and add all the details necessary to fix the issue?

**Comment by XX-Yin** [comment]
> @XX-Yin Can you make a new issue about a nidaq external file, and add all the details necessary to fix the issue?

We can reopen this issue.
