### ISSUE TITLE
Add writing permission to the repo

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#17]
@jsiegle Could you add Alex, @XX-Yin and me to this repo with writing permissions since we're going to develop it together? Please also make sure that the main branch is protected. Thanks!

**Comment by jsiegle** [comment]
What is Alex's GitHub username?

**Comment by alexpiet** [comment]
I'm @alexpiet

**Comment by jsiegle** [comment]
Ok, added both of you and the `main` branch now requires pull requests!
