### ISSUE TITLE
Force Save fails to export to nwb

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#171]
When I use the "ForceSave" function, I get a warning that the export to NWB failed because "could not resolve dtype for VectorData 'animal_response'.

Any idea @XX-Yin ?

**Comment by XX-Yin** [comment]
I think it may be related to the update of the GUI and we need to update the TransferToNWB.py. For example, we deleted the `AnimalName`.
