### ISSUE TITLE
Why do we save a json and nwb?

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#173]
@XX-Yin

**Comment by XX-Yin** [comment]
You mean save json and nwb simultaneously?

**Comment by alexpiet** [comment]
yes

**Comment by XX-Yin** [comment]
I think it's @hanhou who made this change. For me, it's fine to save only Json or both of them. If we only save Json, we can transfer the json to the NWB later.

**Comment by alexpiet** [comment]
Gotcha. I think the NWBs won't save correctly right now because they look for the `Tower` field that I removed. I fixed it in https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/169

**Comment by hanhou** [comment]
I used to convert json to nwb elsewhere, which requires me to maintain a converting code and run it separately. Then I realized it's easier if we do the conversion immediately after a session. Maintaining the conversion code in the same repo ensures that any changes to the json structure will be reflected in the conversion code.

**Comment by alexpiet** [comment]
Should I make a PR to fix the issue with the missing `Tower` field?

**Comment by hanhou** [comment]
> 169

This kind of compatibility issue is exactly what I would like to catch by converting to nwb immediately. It did not crash the GUI, right? Because I have a try-catch around converting to nwb. If so, I can fix it after merging your branch.

**Comment by alexpiet** [comment]
It does not crash the GUI. And I believe #169 resolves the issue

**Comment by hanhou** [comment]
Oh I see. Then it should be fine to wait for 169 being merged.

**Comment by alexpiet** [comment]
ok cool. I tagged you in the PR for 169 at the place where the issue exists so you can look at it
