### ISSUE TITLE
Ephys rig behavior GUI frozen if changing baseline weight and then adding post weight

### ISSUE THREAD

**Issue by ZhixiaoSu** [AllenNeuralDynamics/dynamic-foraging-task#183]
The python GUI on ephys rig gets frozen if I: 1. click 'start' to stop the behavior, 2. then adjust baseline weight (this is a new mouse), 3.  and then update post weight. The data has been lost for two days.

Xinxin and I reproduced this error and it is related to a recent update. @XX-Yin can provide more detail.

**Comment by ZhixiaoSu** [comment]
Closed because I opened it in a wrong place.

**Comment by alexpiet** [comment]
@ZhixiaoSu @XX-Yin Is this issue still happening?

**Comment by ZhixiaoSu** [comment]
This is fully fixed.
