### ISSUE TITLE
make ephys branch/general discussion of ephys code stability

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#189]
We might want to setup an `ephys` branch on github. The idea here is this branch would be more stable than `main` since updates that get tested in the training room might produce different issues on the ephys rigs. 

- advantage - stable, less likely to have unexpected issues during ephys recordings
- disadvantage - no clear procedure for when updates to pulled to `ephys` from `main`. 

@ZhixiaoSu @hanhou @XX-Yin Thoughts? My vote would be against it, because I think the `ephys` branch will drift behind `main` without a clear update policy. 

**implementation notes**
- create branch, pull from `main`, set up branch protection so we require PR, and cannot be deleted. 
- make update script that updates the ephys computers every day to `ephys`
- update Task Scheduler to use the `ephys` daily update script.

**Comment by hanhou** [comment]
I would vote against it too. The current bugs on ephys rigs are not due to updates in behavior rigs, and they should be fixed on both side anyway. In stead of maintaining two branches, we could still use the same branch but be more conservative in updating ephys rigs. For example, we can use semantic versioning on 'main' and only update ephys rig to 'stable' versions.

A side note, we should fix the root cause of critical bugs like data loss by improving the data saving mechanism (eg. saving to disk periodically), in addition to fixing individual bugs that caused GUI crashing, because there are always edge cases that we do not expect.

**Comment by XX-Yin** [comment]
I can image a new ephys branch is difficult to maintain. Even if we have a schedule to merge the `main` to the `ephys`, which means the update flow is from one local branch -> production_testing -> main -> ephys. What if we want to quickly develop some functions related to the `ephys`. Should the flow be changed to local branch -> ephys -> production_testing ->main ?

**Comment by XX-Yin** [comment]
When we make a new PR, should we also test it on ephys rig? Our current testing mainly includes features in the behavior rig, not the ephys rig (such as optogenetics and high speed camera) .

**Comment by ZhixiaoSu** [comment]
I would vote for having a same branch on ephys rig and behavior rigs for the following reasons: 
1. Eventually they should be the same on software end (maybe some differences on the way it controls the lasers/led, but they should be on a separate board), unless we want to use bonsai to record ephys data;
2. It is better to have stable software and data acqusition. If maintaining one branch allows us to do more thorough testing on it, we should focus on optimizing one branch while keep the ephys rig on a more conservative but stable version. (If this allows local development of new functions)
However, I'm not involved in software development. Another key question is when do we expect to have a 'local minimum' version to settle down as a 'stable' version. Before that, it might be nice to have ephys rig stay on something that works but not optimal.

**Comment by alexpiet** [comment]
How about this for a standard procedure.

On monday, as part of the weekly testing cycle:
  - someone (either a scientist, or RA, TBD) tests "production_testing" on a ephys rig. 
  - Specifically testing the optogenetics tools. 
  - this can either happen at a pre-defined time (every monday at 4pm, for example), or just ad-hoc. 
  - Any issues are reported on github
  
On tuesday, at the weekly behavior meeting any remaining issues are discussed, and whether the updates are merged into main.

Other than the specific testing window on monday, the ephys rigs are always up-to-date on the "main" branch, and are automatically updated every morning.

Separately, it would be good to figure out a way to robustly test the optogenetics tools outside of the ephys rig

**Comment by JeremiahYCohen** [comment]
Tagging @jsiegle for visibility and in case he wants to weigh in.

**Comment by jsiegle** [comment]
I think this plan sounds good, and second Alex's recommendation to replicate the opto setup on a test rig.

**Comment by XX-Yin** [comment]
It sounds a good plan. We can also test the high-speed camera in the ephys rig.

**Comment by alexpiet** [comment]
@XX-Yin Do you want to set up a specific time window for testing on the ephys rig every monday? Do you want to be responsible for testing on the ephys rig?

**Comment by XX-Yin** [comment]
I can be responsible for testing on the ephys rig, but it's good to make the testing time more flexible (maybe Monday or Tuesday?).

**Comment by alexpiet** [comment]
The advantage of having all testing done on monday is then we can discuss at the tuesday morning meeting with everyone present. I understand if schedules are tight, but I think it would be good to have testing done by mid-day on tuesday so we can merge updates in a timely manner on tuesday (Like before 4 or 5 pm, so its not a late-night discussion).

**Comment by alexpiet** [comment]
@ZhixiaoSu suggests that @XX-Yin make a dedicated testing instructions so that multiple people can test on monday

**Comment by XX-Yin** [comment]
> multiple

That sounds good! I will make an instruction.

**Comment by alexpiet** [comment]
> > multiple
> 
> That sounds good! I will make an instruction.

Please share with me, and place it on the wiki

**Comment by alexpiet** [comment]
Closing this issue.
- We updated the SOP to include testing on the ephys computer
- We decided against an ephys branch of the code
