### ISSUE TITLE
Cannot convert input to float: , ''

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#191]
This appears to be the root cause of #183. #185 solves this by checking for the attribute, but we should look for the empty widget in the UI file and remove it

**Comment by XX-Yin** [comment]
@alexpiet thanks for checking. I am not sure that I understand this issue. I checked the Frequency in the json file, and it was set correctly. 

What do you mean this parameter does not get set of updated correctly?

**Comment by XX-Yin** [comment]
The frequency of each condition is defined as Frequency_1, Frequency_2, Frequency_3 and Frequency_4 respectively.

**Comment by alexpiet** [comment]
@XX-Yin Sorry for my lack of clarity. I was worried that the Frequency parameters weren't getting saved when altered in the GUI, but I checked and they are. 

The issue is that the individual options within the QCombobox are QLineEdit widgets, so the code that checks for parameter changes iterates through them, but they don't have name fields, so we see the empty widgets. I have a PR to remove the error in this case. 

Everything seems to be working fine! Sorry for the false alarm

**Comment by alexpiet** [comment]
Probably also the cause of this:
15 | Cannot convert input to float: , '' | Foraging.py | keyPressEvent | line 1685 | ephys3

**Comment by alexpiet** [comment]
Happening often.
245	Cannot convert input to float: , ''	Foraging.py	keyPressEvent	line 1765	1B, 1C, 1D, 2A, 2B, 3A, 3C, 3D, 7C, ephys3
