### ISSUE TITLE
Fix warmup

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#213]
- For the record, I'm approving this PR per this dicussion https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/207#issuecomment-1917663223. The issues about warmup will be solved by another PR.

_Originally posted by @hanhou in https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/177#issuecomment-1917698175_

**Comment by hanhou** [comment]
@XX-Yin let's fix warmup bugs and test it thoroughly so that it can be integrated into autotrain.

**Comment by XX-Yin** [comment]
@hanhou Yes, I will find the time sooner! I've been super busy this week and barely had a long stretch of time to work on code.

**Comment by hanhou** [comment]
No problem!
