### ISSUE TITLE
training stage parameters are getting saved

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#229]
long term - the stage parameters should not be changed when the individual sessions parameters are changed
short term - I can set up an auto-job to just copy the training stage parameters from the repo periodically, which will wipe any changes from the individual session parameters

**Comment by alexpiet** [comment]
@hanhou @XX-Yin I can confirm the TrainingStagePar.json files ARE getting modified

**Comment by alexpiet** [comment]
I updated the computers to automatically update the Training stage parameters json file every 30minutes from the version on the repo. This is a short term fix, we need a long term fix

**Comment by hanhou** [comment]
Long term fix would be using AutoTrain instead of using locally saved parameters.
