### ISSUE TITLE
Set up automatic merges for a in_testing branch

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#231]
- Right now, we can't merge PRs onto production_testing from monday morning until some point on tuesday when the production merge happens. 
- This is (1) annoying, (2) prone to errors because we will forget.
- Solution:
   - Enable an automatic pull from `production_testing` into a new branch `in_testing`, that happens on monday morning at like 5am.
   - The testing rig updates to `in_testing` rather than `production_testing`
   - On tuesday we merge `in_testing` into `main`
- This solution will prevent us from having to remember to delay merges into production testing during the monday testing window.
- I think we can use github actions to do this, but I've never used this feature before: [https://stackoverflow.com/questions/35445186/can-github-automatically-merge-branches](https://stackoverflow.com/questions/35445186/can-github-automatically-merge-branches)

Any thoughts @hanhou @XX-Yin

**Comment by hanhou** [comment]
I suggest we rename `production_testing` to `develop`. Github action sounds a good idea.

**Comment by XX-Yin** [comment]
Using in_testing as a medium between Monday and Tuesday sounds like a good idea.

**Comment by alexpiet** [comment]
- created a "develop" branch
- better instructions: https://docs.github.com/en/actions/quickstart
- Details on using a scheduled action: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
- first draft: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/branch_automation/.github/workflows/automerge.yml

**Comment by alexpiet** [comment]
development notes
- [ ] create a github action
- [ ] use the schedule feature
- [ ] create a PR from an action
- [ ] approve or merge the PR from an action
- [ ] put everything together

https://github.com/AllenNeuralDynamics/automation_testing

**Comment by alexpiet** [comment]
This should be resolved by #325 #324 #323
