### ISSUE TITLE
Create a "load last session" button

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#233]
@hanhou 
I'm not sure how this interacts with the auto-training system. But there should be a button that loads the last session from the current mouse, so the RAs don't need to click around and find it.

**Comment by hanhou** [comment]
Is this kind of solved by #206 @XX-Yin ?

**Comment by XX-Yin** [comment]
> Is this kind of solved by #206 @XX-Yin ?

Yes, it's kind of solved in #206, but need to make some changes to load the last session by default.
