### ISSUE TITLE
remaining newscale issues

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#243]
I'm not planning on fixing these issues since we are going to get new lickspout stages soonish, but I'm documenting them in case they become issues in the short term, and they might help when updating the code to the new stages

- The python-newscale repository throws "unprintable" errors, which means if you try to print the error, it throws another error
- The python-newscale repository prints error messages in addition to raising them, which is visually annoying
- Its unclear why we are getting errors from python-newscale to begin with
- Once we lose the connection to the stage, I can't seem to reconnect. I dont understand what the issue is
- The way we wait for feedback from the IOWorker thread is by sleeping the main thread repeatedly, then checking to see if the result is done. This is bad, we should use slots/signals to get feedback asynchronously and trigger a function.
- I'm not familiar with the approach of sending commands to a queue in the IOWorker object, but it seems like there should be a more robust solution.

**Comment by ellahiltonvano** [comment]
@alexpiet I'm going to close this issue since we will soon move away from the newscale system entirely
