### ISSUE TITLE
Need a way to configure which boxes are photometry rigs

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#255]
- This could be a setting in the box specific files?
- Right now StopPhotometry just checks for `self.box_letter== "D"` which is not a robust solution.

**Comment by hagikent** [comment]
Yes, local setting files should contain a flag if this is a photometry rig. Also, considering the possibility that a PC controls more than 2 FPs, local setting files should have COM port info per FP box. However, for 446/447 for foreseeable future, we are rather heading to 1PC/1Box-regime, and thus, this would not be an issue.

**Comment by alexpiet** [comment]
I think we should add entries to the ForagingSettings.json:
```
Photometry_box1: False,
Photometry_box2: False,
Photometry_box3: False,
Photometry_boxD: True
```

The box specific settings files get passed to bonsai, so its better to specify this in the `.json`. This will allow any combination of boxes from a computer to be photometry or not.
