### ISSUE TITLE
Missing fields in processed nwb files

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#256]
We are building behavior+physiology analysis pipeline, and the behavior nwb files will be the basis for that (instead of the temp json file).

I realized that the processed nwb is missing essential fields such as:
-"B_PhotometryRisingTimeHarp"
-"B_PhotometryFallingTimeHarp"

@hanhou also mentions the nwb misses several fields that exist in the json file.

I think, for the future, it's better to make basically all the fields in the json be packaged into nwb.

As the latest GUI has inherited the conversion function from Han's daily routine, assigning this issue to @XX-Yin

**Comment by XX-Yin** [comment]
Yes, there are some fields missing in the NWB due to code updates (we added some new fields).

**Comment by hagikent** [comment]
Great. It would be great if you could keep @hanhou in the loop.

While updating the GUI to fix this, the existing (already packaged) nwb files should be updated/replaced too. For that, [Han's routine service code](https://github.com/hanhou/code_cache/blob/master/sync_bonsai/behavior_pipeline_bonsai.py) has to be updated identically. Thanks!

**Comment by alexpiet** [comment]
You can document this missing fields here: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/197
