### ISSUE TITLE
basic information is not loaded in the training box

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#282]
@hanhou I found that when loading a session in the 447 training box, "info_task" and "info_performance" are not displayed. I checked the code and it seems that they are not saved.

**Comment by alexpiet** [comment]
Can you screenshot what is missing?

**Comment by XX-Yin** [comment]
When we load the session, the panel should display some information.

![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/f33e9668-eee3-451f-bb90-f9563a408f65)

**Comment by alexpiet** [comment]
Why do we want to load that information?

**Comment by XX-Yin** [comment]
> Why do we want to load that information?

I think it's nice to show this basic information. You can quickly get an overview about the session.

**Comment by alexpiet** [comment]
But what is the scenario in which we are using the GUI to get an overview of the session that has already finished? It seems like the streamlit app is the more appropriate place for that kind of information.

**Comment by XX-Yin** [comment]
You can know the metrics immediately from the last session (trials; finish rate; early licking ...) when you load the data, which is complementary to the Streamlit app. This information is shown in the ephys GUI.
