### ISSUE TITLE
multiple "save" options in the File menu

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#291]
Under the "File" button we have:
- Save (calls `_Save()`)
- Force Save (calls `_ForceSave()`)
- Save (without restarting a session) (calls `_SaveContinue()`)
- Save As (calls `_SaveAs()`)

I propose:
- removing `Save (without restarting a session)`, because `_Save()` now defaults to `SaveContinue=1`, so its completely redundant. 
- I think we should keep `Force Save`. 
- I'm 50/50 on keeping `SaveAs()`, since I would like to encourage always saving in the standard spot. @XX-Yin Is this valuable in the ephys room?

**Comment by XX-Yin** [comment]
My opinions are

1. removing Save (without restarting a session)
2. keeping Force Save
3. Keeping SaveAs(). It's still necessary (e.g. we want to save parameters in a different place).
