### ISSUE TITLE
Add indicator for |bias| > 0.7 

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#296]
Steps:
- Calculate bias online (@hanhou has a definition)
- Check for bias outside of a tolerance range at the start of each trial
- Alert the user through either a pop-up, mark on the trial graph, or a text warning (seek RA feedback here)
    - remove the matching plot
    - Moving the legends to the space where the matching plot is now
    - design some indicator for side bias
    - Can then remove the "hide legend" button

**Comment by alexpiet** [comment]
@hanhou Can you provide @micahwoodard a definition of how to compute bias online?

**Comment by alexpiet** [comment]
These two issues might be redundant:
I think this issue is one method for computing bias:
https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/314

I think the resolution of this issue is to compute bias, and remove the matching plot:
https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/313

**Comment by micahwoodard** [comment]
@alexpiet @hanhou the issue says calculate bias online. Are there instances of online calculations elsewhere in the repo or other places? I have not done that before so example code or direction would be helpful

**Comment by alexpiet** [comment]
@micahwoodard By "online" we mean after each trial in the GUI as opposed to calculating the bias "offline" after the session is over. So you will just use a normal function in the code repo that executes either in the main thread, or in a separate thread if its slow.

**Comment by micahwoodard** [comment]
Ohhhhhh okay thank you for that clarification

**Comment by micahwoodard** [comment]
@alexpiet @hanhou Do you want me to import the logistic regression bias functions in the aind-foraging-behavior-bonsai or just implement the functionality within the foraging repo? I see the the logistic regression function linked takes a nwb file as an argument, and  I see that there is a TrasferToNWB py file within the foraging repo, but I'm not seeing where a nwb file is generated or used. Is the idea to generate a nwb based on the GenerateTrials class and then feed that into the logistic regression bias function?

**Comment by alexpiet** [comment]
@micahwoodard We want to implement the functionality into the task repo. 

TransfertoNWB.py is going to be removed soon.

**Comment by micahwoodard** [comment]
Okay that makes sense. In the logistic regression bias function, it seems like it cycles through different models from different papers found [here](https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-models/blob/80361bf594fc99ba6d6558c35308550b0264e1a7/src/aind_dynamic_foraging_models/logistic_regression/model.py#L18C1-L23C2). Are we going with a particular model?

**Comment by alexpiet** [comment]
I defer to @hanhou on this topic

**Comment by hanhou** [comment]
Let's use Su2022. See this comparison: https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-models?tab=readme-ov-file#comparison

**Comment by hanhou** [comment]
I haven't systematically explored the parameters but I think the default values should be fine.
