### ISSUE TITLE
Shaders timer; toggle on port 2 digital output

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#3]
@bruno-f-cruz Hi Bruno, 

1) I manually merged your recent pull request related to the digital input parsing using the updated API as there is a conflict with the current main branch.

The following are just some illustrations of the problem we need to solve.

1) Shader timers. Currently, my workflow is stuck on shader timer nodes.
2) Should I still use Behavior.TimestampedOutputToggle to toggle the port 2 digital output? I can't receive the timestamp. 
![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/11dedf32-d7e2-4f67-ad51-332733396d5c)

**Comment by bruno-f-cruz** [comment]
I dont have an board with me at the moment, but your problem might be the "DistinctUntilChanged". Can you plot the values that arrive at "Value" and "BitWiseAnd" and "DistinctUntilChanged" node simultaneously? Disabling the node will probably be enough to make it work.

**Comment by bruno-f-cruz** [comment]
Check  #4 for a try at solving the first problem

**Comment by XX-Yin** [comment]
Hi Bruno, 

Both of these issues were solved. 

1. I manually merged your pull request related to the shaders timer. It works. I am running some sessions to see how accurate of the shaders timer and will keep you posted. 

2. Disabling the "DistinctUntilChanged" node works.

**Comment by bruno-f-cruz** [comment]
closed by #4
