### ISSUE TITLE
Remove Formal and Temporary logging

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#301]
No reason to maintain both of these

**Comment by alexpiet** [comment]
As far as I can tell, this is only used when starting the camera. However, in the training room we use a camera that is not integrated into the GUI. In the ephys room is this integrated?

**Comment by XX-Yin** [comment]
@alexpiet sorry I missed this message. Yes, the high-speed camera in the ephys rig was integrated into the GUI.
