### ISSUE TITLE
Small differences between water valve opening time and the water volume.

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#341]
The water volume is changed with the valve open time based on the water calibration. We only keep 3 decimal places for valve open time, so the water volume may show small differences when we set it based on the valve open time. 

For example, in the case shown below, where R(ul) is set to 3, R(s) will be set to 0.034. If we set R(s) to 0.034, R(ul) is not exactly 3, but 3.01.

![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/40271ddf-8e6d-4036-b696-b2d107785800)

**Comment by alexpiet** [comment]
@XX-Yin Should increase the precision of the valve open time? Or should we accept this level of variability?

**Comment by JeremiahYCohen** [comment]
I don't think we have the resolution to measure 10 nl with these valves.

**Comment by XX-Yin** [comment]
I think we can accept the variability that is much smaller than the calibration precision we can achieve.
