### ISSUE TITLE
Software version issues

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#387]
- [x] @XX-Yin says that the ephys rigs use a different version of python. We need to ensure the same version of python are being used on different rigs
- [x] Matplotlib is pinned to version 3.5.3 in the requirements.txt, but not in the pyproject.toml file. Why do we need this version? Do we actually just need some minimum version?
- [x] https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/381 moved the minimum python version from 3.8 to 3.9, this was not documented, and we should be on the look out for bugs that have been introduced by this change. Upgrading python to 3.9 introduces a breaking dependency on matplotlib==3.5.3. As a result the installation instructions are now incorrect. Users must now:
    - create a conda environment with python 3.9
    - pip install -e . the repo
    - pip install --force-reinstall -v "matplotlib==3.5.3"

**Comment by hanhou** [comment]
I also have a hard time with the dependencies. I cannot import `harp` 

```
>>> import harp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\anaconda3\envs\bonsai_gui\lib\site-packages\harp\__init__.py", line 1, in <module>
    from harp.io import REFERENCE_EPOCH, MessageType, read
  File "C:\Users\admin\anaconda3\envs\bonsai_gui\lib\site-packages\harp\io.py", line 5, in <module>
    from pandas._typing import Axes
  File "C:\Users\admin\anaconda3\envs\bonsai_gui\lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\admin\anaconda3\envs\bonsai_gui\python.exe"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/24734299/e8eaaeb2-0aed-47e4-9ff8-c2b68bfcfd97)

**Comment by XX-Yin** [comment]
This seems to be related to package dependencies. Did you directly install all packages by running "pip install -e ."?

**Comment by hanhou** [comment]
Okay, reinstall the conda environment seems to solve the issue.

**Comment by alexpiet** [comment]
@hagikent @KanghoonJ Be aware that #381 requires upgrading to python 3.9. Users must reinstall the conda environment. This PR will get merged into `main` next tuesday. You can upgrade before then.
1. Remove old conda environment: `conda remove -n Foraging --all`
2. Delete any remaining environment files: Check in ` ~/anaconda/envs/Foraging` or `~/miniconda/envs/Foraging`
3. Create new conda environment `conda create -n Foraging python=3.9`
4. Use pip to install the repo: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/wiki/Installation-Instructions#use-pip-to-install

This may cause the bonsai executable `bonsai.exe` to become unstable. If this happens bonsai will crash randomly. To resolve this issue: 
1. navigate to `dynamic-foraging-task/bonsai` and delete all the three folders `Extensions`, `Gallery`, `Packages`, as well as all `*.exe` and `*.exe.settings` files. 
2. Run the `setup.cmd` script

**Comment by alexpiet** [comment]
Resolved the last issue by forcing everyone to update to python 3.11
