### ISSUE TITLE
Input checking for settings files

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#390]
We load information from the following text files:
- ForagingSettings.json
- Settings_box#.csv
- WaterCalibrationPar_#.json
- WaterCalibration_#.json
- LaserCalibration_#.json

Typos or other errors in formatting should we checked when we load the file. I dont think we need to adopt a full pydantic schema (at least at the moment). However we should check for errors and alert the user rather than waiting for bonsai to crash. Bonsai is very sensitive to typos, newline characters, and extraneous fields in the settings.csv file. Currently errors cause crashes without clear debugging information.

**Comment by rachelstephlee** [comment]
I have access to the ForagingSettings and the Settings_box, but can someone send me the Water and Laser calibration json files (I'll need all 3). 

I am assuming that the json and csv will always have those exact same fields as default, and users can input their own dictionary of fields to check if not.

**Comment by alexpiet** [comment]
Thinking about it more, I'm not sure we need to worry about the water and laser calibration files for now. Since they are generated by the GUI. 

The json and csv files may have additional fields, and that is allowed. They may also not have some fields. The code already checks for the mandatory fields in the ForagingSettings.json. 

The bigger issue here is that bonsai crashes when there isn't a newline at the end of the last entry in the csv file:
bonsai crashes:
```
key,value
```

bonsai is fine:
```
key,value

```

**Comment by rachelstephlee** [comment]
Thanks for the clarification. I'll just check for newline at the end and I'll enhance the error checking in ForagingSettings.json then!

**Comment by rachelstephlee** [comment]
Newline issue fix is in for now. Please let me know if there is a list of mandatory fields for the Settingsbox csv file I should incorporate. If not, we can merge the branch and close this bug.
