### ISSUE TITLE
Need a policy for updates with manual intervention

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#393]
By manual intervention, I mean a user must take some action on each computer to make the code runs. Examples:
   - Need to add/modify an entry in a `.json` or `.csv` file
   - Need to install a python package

I have been manually updating the computers in 447. But now that we have computers in the ephys room and 428, this approach needs a precise policy. I propose:

- [x] Add a section to the pull request templates that prompts for `manual interventions`
   - We add specific steps that need to be taken, and when (do you need to wait for the updates to merge? Can you do them ahead of time) 
- [x] Have designated users that are responsible for the manual interventions on their computers.
   - Ephys3: Xinxin
   - Ephys1: Kanghoon
   - 428 Computers: Kenta
   - 446/447: Whoever implements the breaking change (Alex, Han, Xinxin)   
- [x] Document this policy in the SOP [Software Update Procedures](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)

Thoughts? @hanhou @XX-Yin @KanghoonJ @hagikent

**Comment by alexpiet** [comment]
I created a PR to update the PR template

**Comment by JeremiahYCohen** [comment]
Looks great. Let's add a secondary responsible person for each (in case someone is away). How about this?
Ephys 3: Xinxin (primary), Kanghoon (secondary)
Ephys 1: Kanghoon (primary), Xinxin (secondary)
428: Kenta (primary), ? (secondary)
446/447: Alex, Han, Xinxin

This comment generally speaks to a major issue in how we communicate updates. We need _everyone_ to buy into the protocol for implementing updates. We'll discuss this at the next software meeting.
