### ISSUE TITLE
Generating session metadata from the GUI

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#402]
- Behavior session metadata
  - Which fields should go to the behavior session metadata?
  https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/303#issuecomment-2062196234
  - Existing fields in the behavior GUI
     - [x] experimenter_full_name
     - [x] session_start_time
     - [x] session_end_time
     - [x] subject_id
     - [x] session_type
     - [x] animal_weight_post
     - [x] water calibration
     - [x] laser calibration
     - [x] reward_consumed_total
     - [x] reward_consumed_unit
     - [x] adding training stage
  - Missing fields from the current behavior json?
     - [x] Ephys recording information 
     - [x] Ephys probe configuration
     - [x] Probe target
     - [x] Ephys probe manipulator coordinates
     - [x] Stick microscopes configuration 
     - [x] Camera start/stop time
     - [x] iacuc_protocol
     - [x] protocol_id
     - [x] rig_id (rig metadata)
     - [x] data_streams
        - [x] behavior
        - [x] video
        - [x] ephys
     - [x] reward_delivery
     - [x] stimulus
        - [x] optogenetics
        - [x] auditory cue
      - [x] box name 
  - To do:
    - [x] Generating metadata directly at the end of each session.
    - [x] Generating metadata from input json files.
    - [x] Handle edge cases.
    - [x] Generating metadata for old sessions with some fields missing.

- Ephys session metadata

- Related repo: 
   - https://github.com/AllenNeuralDynamics/CTLUT-metadata-gen/tree/main/src/CTLUT_metadata_gen
   - https://github.com/AllenNeuralDynamics/aind-metadata-mapper
   - https://github.com/AllenNeuralDynamics/aind-data-schema

- Related discussion: 
   - https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/68
   - https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/303#issuecomment-2062196234

- Online app:
   - https://metadata-entry.allenneuraldynamics.org/

- Questions/Issues
    - [x] What is Modality.TRAINED_BEHAVIOR? 
        - old version
    - [x] What is the stimulus device name for TRAINED_BEHAVIOR?
        - old version
    - [x] Distance between the two lick spouts?
        - [x] We should define the lick spout reference position. 
    - [x] adding "Face side left" and "Face side right" to devices/CameraTarget
        - [x] Saskia will make changes.
    - [x] OptoStimulation needs changes there are other protocols and the stimulation period is also flexible. It is better to extract information from NWB. Make fields in the OptoStimulation optional)
         - [x] Go to stimulus epoch
    - [x]  `mouse_platform_name` and `active_mouse_platform` are only necessary for behavior data stream.
    - [x] Is data description necessary?
    - [x] Combine different data streams
       - Separate different streams are much more flexible.
    - [x] Missing `Laser` in `STIMULUS_DEVICES` (rig.py)
    - [x]  Missing `Fujinon` in `LENS_MANUFACTURERS` (organizations.py) https://github.com/AllenNeuralDynamics/aind-data-schema-models/issues/4
    - [x] Missing organization `Midwest Optical Systems. Inc.` in `Organization` (organizations.py). https://github.com/AllenNeuralDynamics/aind-data-schema-models/issues/5
    - [x] https://github.com/AllenNeuralDynamics/aind-data-schema/issues/920
    - [ ] https://github.com/AllenNeuralDynamics/aind-data-schema/issues/926
    - [ ] https://github.com/AllenNeuralDynamics/aind-data-schema/issues/927

**Comment by alexpiet** [comment]
@XX-Yin Have these remaining tasks been resolved? If not can you either resolve them or assign someone?

**Comment by XX-Yin** [comment]
@alexpiet most of these issues have been solved. Some issues don't have a short-term solution.

**Comment by alexpiet** [comment]
> @alexpiet most of these issues have been solved. Some issues don't have a short-term solution.

Can you mark off the ones that have been resolved, and make a separate issue for each remaining one?
