### ISSUE TITLE
Post Weight is set when loading from file

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#406]
@henryloeffler reported this happening today in 447

**Comment by alexpiet** [comment]
It looks like the current behavior is that the post weight is loaded when you load the mouse, but if you press `start`, its cleared. That seems to make sense to me. @hanhou @XX-Yin ?

**Comment by XX-Yin** [comment]
Yes, you are right!
________________________________

**Comment by alexpiet** [comment]
Closing this issue, since the field is correctly cleared when the session starts. Long term we should separate the concept of "Session ended" and "new session" which might give clarity here
