### ISSUE TITLE
Documentation for preparing Harp sound boards

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#407]
Current `Deployment` section is lacking documentation for preparing sound board - **what sound/bit file** should be uploaded to **which channel** and **how**.

Sound-board GUI software seems to be buggy and often doesn't work properly on Helio-Pogo PCs (although preparation can be done in non-experimental PCs). General documentation may be better if it's based on the Bonsai-based file uploading, which Neurogears recently demonstrated during the monthly meeting.

**Comment by HeRodrgues** [comment]
I had a similar problem four years ago, and that computer also had an i9 CPU, but we didn't depend on the GUI to upload the sample.
My laptop has an AMD Ryzen 9, and I have the same problem.
I think that this error is somehow related to the Sound Board GUI using a legacy National Instruments package that doesn't work with the more recent CPUs.
Should we ask Neurogears to help make uploading the sound sample through Bonsai easier?

**Comment by hagikent** [comment]
migrated to behavior blog as more relevant to the "installation wiki" there.
