### ISSUE TITLE
'GenerateTrials' object has no attribute 'CLP_CurrentDuration'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#415]
'GenerateTrials' object has no attribute 'CLP_CurrentDuration' | MyFunctions.py | _PerformOptogenetics | line 214 | 1C
06:00:57 PM:ERROR:MyFunctions:MyFunctions.py:_PerformOptogenetics:line 214:'GenerateTrials' object has no attribute 'CLP_CurrentDuration'

**Comment by XX-Yin** [comment]
This was an error caused by me. I wrongly set the optogenetics parameter. We can check whether the parameter are set correctly to avoid this error.
