### ISSUE TITLE
Documention needed for 446 PCs – Lickport stage

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#425]
To setup 446 PCs, [installation instruction wiki](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/wiki/Installation-Instructions#conda-installation-of-the-repository-fails) has to be updated to include:

1A. New lickport-stage Harp devices that are replacing Newscale stages.
@Poofjunior @bruno-f-cruz 
1B. Is the foraging main branch already compatible with the new lickport-stage? I guess `ForagingSetting.json` is also getting obsolete?
@alexpiet @XX-Yin 

2A.High-speed videography setup, including cable connections and `Settings_boxN.csv` config.
@ZhixiaoSu 
2B. Is the foraging main branch already utilizing the `AIND-FLIR` node, with which we don't have to setup/hardcode camera settings using SpinView?
@alexpiet @XX-Yin @bruno-f-cruz 
__
It would be great if you could update the wiki at your earliest convenience so we (@yonibrowning @hagikent ) can finish setting up 446 PCs, thanks!

**Comment by ZhixiaoSu** [comment]
Will do later today!

**Comment by bruno-f-cruz** [comment]
Hey. No idea about the state of any of those points. I am happy to help if you need. Feel free to schedule a meeting to go over it.

**Comment by alexpiet** [comment]
> To setup 446 PCs, [installation instruction wiki](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/wiki/Installation-Instructions#conda-installation-of-the-repository-fails) has to be updated to include:

I've updated the information I know

> 1A. New lickport-stage Harp devices that are replacing Newscale stages. 1B. Is the foraging main branch already compatible with the new lickport-stage? I guess `ForagingSetting.json` is also getting obsolete? 

The new lick spout stages are not yet compatible, but in progress.

> 2A.High-speed videography setup, including cable connections and `Settings_boxN.csv` config. 2B. Is the foraging main branch already utilizing the `AIND-FLIR` node, with which we don't have to setup/hardcode camera settings using SpinView? 

The `main` branch is compatible with the high speed cameras. I have included the information I know in the wiki. @XX-Yin Can you (1) document how to find the COM ports for the AIND lick detectors? (2) Document how to find the serial number for the high speed cameras?

**Comment by XX-Yin** [comment]
(1) I just unplugged and plugged in the Harp USB cable to find the COM port. One trick is that the COM port you just plugged in always appears at the end of the list (can be visualized from the behavior node in the bonsai; shown below). 
![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/e9542d0b-86e1-4296-b694-774d51fb8da5)
(2) The serial number of the camera can be viewed from the SpinView software.

**Comment by alexpiet** [comment]
Thanks @XX-Yin Can you add that to the wiki instructions?

**Comment by XX-Yin** [comment]
> Thanks @XX-Yin Can you add that to the wiki instructions?

@alexpiet Updated

**Comment by alexpiet** [comment]
@hagikent How is the documentation going for 446? Is this issue resolved?

**Comment by hagikent** [comment]
@alexpiet 
I have no idea on Lickport stage, and documentation for it.

Documentation for High-speed videography was set up by @ZhixiaoSu and it worked for me. @yonibrowning had some troubles but it was utilized to update the doc; I think it's now good.

**Comment by alexpiet** [comment]
I will handle the lick port stage documentation when its ready
