### ISSUE TITLE
No camera trigger file found

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#442]
@avalon-amaya reported this happening on 3D in the session ending at 3:31. 

Any ideas @hagikent ?

**Comment by avalon-amaya** [comment]
Happened on 2D too. 
stopped excitation > stopped Thor bonsai > save > window popup "Please restart FIP" > "no camera trigger file found" in warning box.

**Comment by hagikent** [comment]
"Please restart FIP" > "no camera trigger file found"
 I guess this is happening in the GUI...? (or in the Workflow?) I have no idea what the camera trigger file is.

**Comment by alexpiet** [comment]
This has nothing to do with the FIP workflow, it was just noticed on the FIP rigs. The issue is that we check for dropped frames in the camera trigger file, however this file only exists if high speed video was collected. We need to change the logic to only look for this file if we are recording video.

Separately, the way we are logging warnings in the GUI is confusing. We have a specific place for each warning, but that means that the warning dialog box feels messy and unorganized. I'll make a separate issue

**Comment by avalon-amaya** [comment]
This is also happened in 3B today. I had to scroll the warning box to see it. not confined to D boxes.
