### ISSUE TITLE
Organize warning labels in GUI window

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#444]
Right now, each different warning message has a specific location in the warning box. Which means warnings appear haphazardly, and are sometimes missed because they are below the current view (user would need to scroll down). We should:
- Display warnings as a queue, first one to be generated appears at the top. 
   - If a warning can be removed, then the queue is adjusted
   - PyQt listview might be a good tool for this
- Alternatively, we could simply see if we are currently using all the warnings, and condense the remaining ones. Probably order the warning locations by frequency of use. Some warnings are no longer relevant because we added a pop up alert.

**Comment by micahwoodard** [comment]
@alexpiet how do you feel about using a logging QueueHandler? I was thinking use it something like this? 

https://github.com/user-attachments/assets/47564f46-e606-42b4-8ecf-ab3242daa627


```import logging
from multiprocessing import Queue
from logging.handlers import QueueHandler
from random import randint
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QLabel
import sys

def check_warning_queue():
    while not queue.empty():
        label = QLabel(str(queue.get().getMessage()))
        layout.insertWidget(0, label)


if __name__ == '__main__':
    app = QApplication(sys.argv)

    logger = logging.getLogger(__name__)

    # configure stream handler to output console
    stream_handler = logging.StreamHandler()
    stream_handler.setLevel(logger.root.level)
    logger.root.addHandler(stream_handler)

    # configure queue handler to write to queue
    queue = Queue()
    queue_handler = QueueHandler(queue)
    queue_handler.setLevel(logging.WARNING)
    logger.root.addHandler(queue_handler)

    # configure widget to display warnings on
    widget = QWidget()
    layout = QVBoxLayout(widget)

    warnings = ['this is a warning', 'this is also a warning', 'this is a warning too', 'Warn warn warn',
                'are you warned yet?']

    warning_timer = QTimer(timeout=lambda: logger.warning(warnings[randint(0, 4)]), interval=1000)
    check_timer = QTimer(timeout=check_warning_queue, interval=1000)

    warning_timer.start()
    check_timer.start()
    widget.show()

    logger.error('HELLLLPPPP')

    sys.exit(app.exec_())
```

That way we could make all of the warnings log warnings and adding new warning would be simple. I'm not sure how you would remove warnings that were no longer an issue though and also I'm unsure if RA's are looking for specific warnings. Just an idea so lemme know what you think

**Comment by alexpiet** [comment]
Yes, that would be a great solution!
