### ISSUE TITLE
Session metadata - Need to set IACUC protocol and Project name from behavior schedule

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#466]
We need to coordinate with @jackieswapp to add the following information to the behavior schedule, and RAs need to add the following fields to the metadata dialog when starting a new mouse
- IACUC protocol
- Project Name

Steps:
- get python access to smart sheet, or move schedule to excel
- Have GUI auto fill in these metadata fields when the mouse is loaded. Probably just on the first day of training.

**Comment by jackieswapp** [comment]
There are already columns for IACUC protocol and project name on the schedule and queue, they just need to be filled out. 

@alexpiet Would it be easier for python to access a schedule on excel or smartsheets? The schedule/queue/past mice are all on smartsheets currently, but I would very happily abandon smartsheet if that's helpful

**Comment by alexpiet** [comment]
@jackieswapp Can you start enforcing that scientists fill out the IACUC protocol and project name fields? Presumably that information is already being tracked somewhere else?

I'm not sure what is easier excel or smartsheets, I will investigate and get back to you. Is the plan for this schedule to (eventually) move to slims?

**Comment by alexpiet** [comment]
Resolved by #528
