### ISSUE TITLE
Session metadata - go_cue_decibel

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#468]
Right now this is hard coded at 60 dB in the default settings. I'm not sure how this level is set. Is that a thing that needs to be calibrated? Should this value get placed in the rig metadata? Or does it belong in the session metadata because it could be a parameter that gets changed on a session by session basis?

UPDATE:
We should determine a calibration scheme for the sound level. The bonsai workflow needs to be modified to allow sound calibration, and the setting should be saved in Setting_box.csv. Then we need to calibrate each rig.
In progress here: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/475

**Comment by JeremiahYCohen** [comment]
Yes, we should measure speaker output in each rig. Rig metadata should have calibration curves. Session metadata should include stimuli used in the experiment (e.g., dB).

**Comment by hagikent** [comment]
Working on this while consulting Galen and Anna, who have proper auditory research experience/training.
Apparently we have been borrowing the measurement device from Shawn's group but we should have one for 446/447.

**Comment by ZhixiaoSu** [comment]
@mlee10201 and I finished point calibration in 446. Decibel level is saved in ForagingSettingsand attenuation level is saved in SettingX.csv. We also wrote down a point calibration SOP. https://alleninstitute.sharepoint.com/:w:/s/NeuralDynamics/EQcHJUHVyWFCjta-ljVzlYoBYDyVXBhlQoMZB7NUfjir-g?e=ToJQLt
And yes, we have two decibel scales of our own now, one in 347, one in 446.

**Comment by alexpiet** [comment]
Great @ZhixiaoSu ! Can we close this issue?

**Comment by ZhixiaoSu** [comment]
Yes!
