### ISSUE TITLE
Session metadata - Need to ensure FIP data is accurately recorded

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#471]
@hagikent You should review the session.jsons created to ensure the information is accurate.
- special attention that `FIPMode` is recorded

**Comment by alexpiet** [comment]
@hagikent Any feedback?

**Comment by jeromelecoq** [comment]
Related to issue 50 on aind-physio-arch

**Comment by rachelstephlee** [comment]
https://github.com/AllenNeuralDynamics/aind-physio-arch/issues/50

**Comment by hagikent** [comment]
Yes, confirmed. Some additional suggestions pushed back by Saskia were not fully addressed but I believe it's fine for now.
