### ISSUE TITLE
Make "force save" more visible, robust to bonsai disconnection

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#476]
If the user presses save and a trial has stalled, we display a warning saying waiting for the last trial to finish. 

Perhaps if the user presses save again, we offer to save without waiting (force save) ?

**Comment by alexpiet** [comment]
@yonibrowning Reports that `force save` did not work after bonsai disconnected. We should ensure that it is robust. Additionally, if when waiting for the last trial to finish, if bonsai has disconnected, we should automatically force save.

**Comment by ellahiltonvano** [comment]
@alexpiet session data is saved frequently during the session, correct? If so, what data is saved by usingForce Save that wouldn't already be saved?

**Comment by alexpiet** [comment]
We can close this issue, its from before we had saving on each trial
