### ISSUE TITLE
Need to manually update bonsai workflows after pulling from github

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#48]
- The bonsai workflow files are version controlled in this repository.
- After pulling new updates, if a computer has specific configurations they need to be manually updated. For example, disabling the opto settings. 
- We should have a solution that handles this automatically, one to reduce the amount of steps in updating code, and two to reduce chances of mistakes.

**Comment by alexpiet** [comment]
@hanhou @XX-Yin and I discussed this
- The issue is that some settings in Bonsai are rig specific (@XX-Yin can you document which settings?). Thus, when we pull from github those settings are not preserved.
- One option is to separate the bonsai workflows from the GUI repo. The workflows are updated less often, and so we can reduce this issue. This solution is relatively easy to implement, but we worry about having multiple repositories
- The other option is to save all rig specific parameters in a settings file on the computer. We aren't sure how exactly to implement this with Bonsai. (@XX-Yin can you contact Neurogears and investigate?)

**Comment by XX-Yin** [comment]
Specific settings for each rig.

1) Harp behavior COM port (saved in a csv file).
2) Sound card COM port (saved in a csv file).
3) OSC ports (saved in a csv file).
4) Camera USB ports (manually set; the camera is in a different bonsai workflow, and we only need to update the USB ports when we restart the computer). 
5) Photometry ROI ... (@hagikent can you provide more information about the photometry-specific settings?)

**Comment by hagikent** [comment]
For FP:
5. Photometry ROI -> I'm not sure for "Regions" property in `ROIactivity`. I'm consulting Bruno if there is a neat way.
6. Serial numbers for SpinakerCapture (can be easily externalize in a csv file)
7. Camera USB ports (can be easily externalize in a csv file).   *same as #4 but here cameras are recorded

**Comment by alexpiet** [comment]
@XX-Yin Regarding issue 4 about the Camera USB ports. They need to be manually set everytime the computer is restarted? Can we automate that?

**Comment by XX-Yin** [comment]
> @XX-Yin Regarding issue 4 about the Camera USB ports. They need to be manually set everytime the computer is restarted? Can we automate that?

Yes, I think we can automate this using a similar approach to automating the Harp COM port. I need to test this.

**Comment by hagikent** [comment]
For the past couple weeks, I see it (Genetric Camera index) frequentry changed. Might be due to physical unplug/replug.

Note, this will not be an issue once cameras are replaced with high-speed videography where you can specify Serial# (exactly the same as Point6). However, considering not all rigs will have it replaced, having a solution at this point sounds nice.

**Comment by alexpiet** [comment]
- related to https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/16

**Comment by alexpiet** [comment]
@XX-Yin I believe we can close this issue (and #16, and https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/93, which are redundant) now that the fiber photometry workflow has been removed from the rest of the bonsai workflow. What I mean by that is now a `git pull` from origin/main on dynamic-foraging-task will run on all the rig computers without any manual interventions. 

Do you agree? 

#50 is still active, but that is a separate issue.

**Comment by XX-Yin** [comment]
Yes I agree.

**Comment by alexpiet** [comment]
Closing this and related issues
