### ISSUE TITLE
Faster refresh rate on GUI plots

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#480]
Is your feature request related to a problem? Please describe.
@travisjramirez and @NgD-Huy request that the GUI plots refresh more frequently so that they can observe mouse licks.

Describe the solution you'd like
I believe that the GUI updates the graphs at the start of each trial, but especially with delay periods for early licking, that period could get longer. We should update the GUI so that it refreshes (in a thread) more frequently, maybe every 100ms?

Moving from: https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/407

**Comment by galenlynch** [comment]
It seems like online like visualization would be well handled by bonsai.

**Comment by hagikent** [comment]
If there is no other motivation to make the GUI refresh faster, besides plotting licks, I will take care of it rather in Bonsai and close this.
See https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/499
