### ISSUE TITLE
Generating metadata for old sessions 

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#482]
We need to generate session and rig metadata for old sessions with some fields missing.

**Comment by hagikent** [comment]
I have been working on this as a part (and extension) of photometry hackathon.
We have roughly three data categories:
1. 20240528-; basically have rig and session metadata (session meta generation success rate is low, ~80%)
2. 2024 early (-0527); rig metadata backfilling is done; session metadata backfilling will be done next week
3. 2023 late; rig names are different (eg Blue-1), I will finish this in 2-3days; session metadata backfilling will be done next week

adding @rachelstephlee for potential help

**Comment by hagikent** [comment]
2 and 3 are done and ready for mass-uploading.
I would wait for a while for 1; session metadata generation success rate issue (#569 ) should be solved first.

**Comment by hagikent** [comment]
@alexpiet @XX-Yin @hanhou @ZhixiaoSu @galenlynch 

`session.json` and `rig.json` metadata backfilling is done for old data and organized into the following locations.
Before mass-uploading, it would be great if you could take a look. I will start uploading the data early next week (7/15-).
Note, some info is inevitably inaccurate – e.g. as rig config has been frequently changed and impossible to track changes, rig.json is defined in the future relative to when data collection was done.

___
2. 2024 early (-0527): \\allen\aind\scratch\svc_aind_behavior_transfer\2024early_DataNoMetadata_Reorganized
    (1432session, 69sessions don't have metadata due to either no-behavior or stopped immediately)

3. 2023 late: \\allen\aind\svc_aind_behavior_transfer\2023late_DataNoMeta_Reorganized
    (179sessions, 19sessions don't have metadata)

**Comment by hagikent** [comment]
Two updates:
1. David suggests uploading them directly to s3 public bucket and wants Saskia to double-check metadata integrity. Saskia is now working on it.

2. Especially data from 2023late data lacks AAV injection information in the corresponding NSB surgery requests, from which `procedure.json` is created, because surgeries were performed before TARS was integrated. We will be back-filling the surgery request forms and it would take some time. Some help might be required too as it will be pretty much a manual input labor.

**Comment by XX-Yin** [comment]
@hagikent 
For the surgery request back-filling, should each scientist do it for their own mice? What information is needed?

**Comment by hagikent** [comment]
>should each scientist do it for their own mice?

Yes, and the info that should be backfilled would be TARS Lot# and titre.

**Comment by XX-Yin** [comment]
We should let other scientists know this in the next behavior meeting

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hagikent** [comment]
I'm ooo. Can you do that next week? 
Anyways, it's only you @ZhixiaoSu @KanghoonJ 
circling @rachelstephlee as she is developing session-query functions based on metadata.

**Comment by ellahiltonvano** [comment]
@hagikent, looking through the backlogged issues, has this issue been addressed?

**Comment by hagikent** [comment]
Thanks @ellahiltonvano . I'm closing this as it has been addressed at least within the scope of this thread. (still work in progress in the context of physio-arch but that's another story...)
