### ISSUE TITLE
FIP rigs and dropped frame detection 

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#489]
Saved video data, but no camera trigger file found | Foraging.py | _check_drop_frames | line 524 | 1D, 2D, 3D

This seems to be happening on all three FIP rigs. I'm not sure how the camera trigger file is generated, but it somehow isn't getting generated when the FIP rigs trigger video collection

**Comment by hagikent** [comment]
Likely because ThorFIP bonsai is independently recording behavior videos.
How critical is this? If not at all, if can just ignore for now and switching to high-speed videography will automatically solve this.

**Comment by alexpiet** [comment]
Not critical at all. I think its fine to wait for high speed videography. But lets add some logic to the code to stop the error from being thrown.
