### ISSUE TITLE
Subject name mismatch between metadata and file name

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#49]
Sometimes the metadata does not match the saved json file name. I noticed this bug during a sanity check in my data pipeline:

<img width="1230" alt="image" src="https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/24734299/ccb1dd76-120f-46bb-a2db-4813a5797aa9">

Looking at the raw json file, it appears that the `subject_id` field was changed **_within a session_**:

<img width="632" alt="image" src="https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/24734299/b3cc1f30-c624-4592-9f87-2c7d12837643">

I guess what happened was that the RA corrected the `subject_id` _**after**_ session start. This will be a huge problem for data integrity. To avoid this:

1. I'll ask RAs, whenever they find a metadata error, to stop the session, clear the data, and start again.
2. @XX-Yin Please disable those metadata fields in the GUI when a session is running. A better way maybe to disallow this kind of trial-by-trial changes in metadata.

**Comment by XX-Yin** [comment]
Thanks Han. Yes, I agree to disable these metadata fields during running.
