### ISSUE TITLE
Session metadata - Error generating session metadata: bad operand type for unary -: 'str'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#494]
Error generating session metadata: bad operand type for unary -: 'str'
Foraging.py
_Save
line 2389
ephys3

**Comment by alexpiet** [comment]
@XX-Yin This error was generate 548 times last week, all of them on ephys3. I suspect its a type issue with the rig metadata being generated on the ephys rig?

Error generating session metadata: bad operand type for unary -: 'str' | Foraging.py | _Save | line 2415 | ephys3

**Comment by XX-Yin** [comment]
@alexpiet I think so. There is no rig metadata detected in that rig due to mismatch of the prefix, which has been fixed. It should be solved now.

**Comment by alexpiet** [comment]
@XX-Yin Reopening this because it happened last week:
793 | Error generating session metadata: bad operand type for unary -: 'str' | Foraging.py | _Save | line 2448 | ephys3
