### ISSUE TITLE
Remove the TrainingStagePar.json on each rig

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#497]
Now that all mice are on Autotrain, is this system outdated? @hanhou

**Comment by hanhou** [comment]
Yes, it makes sense to me. @XX-Yin any objections?

**Comment by XX-Yin** [comment]
I have no objection. It seems that Sue is still using the training stage parameters.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexpiet** [comment]
@ZhixiaoSu Are you still using the TrainingStagePar.json separately from the AutoTrain curriculum?

**Comment by ZhixiaoSu** [comment]
No, I’m not using it. It was copied there before the auto-train to make sure all rigs have same parameters for each stage. I think if everyone is using the auto-train, we can remove it.
