### ISSUE TITLE
Add real time indicator of lick detector

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#499]
RAs request a visual indicator of lick detection to help with positioning the lick spouts. 

STEPS:
Check for incoming harp messages, add a little indicator to the GUI

**Comment by hagikent** [comment]
Does this have to be in the GUI? I don't know if the visualization in the GUI is fast enough. 
Instead, having a bonsai visualizer window would be more simple/straightforward and real-time?
e.g.
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/54397345/3f22b3c9-f3b1-4c8a-a1ee-c89fde873782

**Comment by hagikent** [comment]
It looks duplicated with: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/480
Seemingly @galenlynch thinks the same as I do?

@travisjramirez @NgD-Huy 
Can you guys watch the video linked in the above comment and let me know if this is enough for your need? Thanks.

**Comment by NgD-Huy** [comment]
This looks great, thank you

**Comment by travisjramirez** [comment]
Is the idea that both left and right licks will appear on the same GUI or will two separate windows open?

**Comment by hagikent** [comment]
one window containing both Left/Right. might be possible to be integrated to the behavior video windows to reduce total number of windows
(this particular example is from a single-lick spout behavior)

**Comment by travisjramirez** [comment]
One window would be great because we can always minimize! And you're correct the less extra windows the better.

**Comment by hagikent** [comment]
After confirming that it doesn't have to be the python GUI-level implementation with @alexpiet , I will work on it.

**Comment by alexpiet** [comment]
- I dont care if we implement things in bonsai or python. 
- But if we do use bonsai, I request that (1) the left/right licks are combined, (2) users can close the lick viewer without disrupting the task, and (3) preferably, the lick viewer would be hidden/closed by default

**Comment by alexpiet** [comment]
I dont know either. Probably fine to skip for now
