### ISSUE TITLE
Can not toggle reward

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#5]
@bruno-f-cruz 
Hi Bruno,

I just found the new workflow can't set the reward duration. When there was a "Manual Water_Left" or "Manual Water_Right" coming in, the reward was just turned on or turned off. It seems that it never uses the "LeftValueSize" or "RightValueSize". This issue only exists for the updated workflow, not in the previous workflow. I am not sure if it relates to the update of the API.  

![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/c7329a21-00f8-4f22-b234-327171594682)

**Comment by bruno-f-cruz** [comment]
At some point, you added the pulse mode to the DO responsible for the cue
no? When you define the value of this register you must pass all the flags
that correspond to the pins you want to use in pulse mode. You need to add
the masks of these outputs as well to that message.

**Comment by XX-Yin** [comment]
Can you also modify this workflow and make a pull request?

**Comment by XX-Yin** [comment]
It solved the problem. Thanks!
