### ISSUE TITLE
Redundant documentation with AIND-Behavior-blog should be removed.

### ISSUE THREAD

**Issue by yonibrowning** [AllenNeuralDynamics/dynamic-foraging-task#513]
It seems as though [the behavior-blog documentation](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Computer-Configuration) has replaced [the dynamic foraging gui documentation](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/wiki/Computer-Configuration-%5BNotes,-copy-from-aind%E2%80%90behavior%E2%80%90blog%5D). This can be confusing as only the former has been kept up to date.

**Comment by alexpiet** [comment]
deleted the copy on the gui repo
