### ISSUE TITLE
KeyError: 'Laser_2'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#520]
FATAL:KeyError: 'Laser_2' | Foraging.py | exception_hook | line 4095 | ephys3

@XX-Yin

**Comment by alexpiet** [comment]
Also generating:
1 | Laser_2' | Dialogs.py | _Frequency | line 182 | ephys3

**Comment by ellahiltonvano** [comment]
This seems like an issue that is now captured by autogenerated issues, closing.
