### ISSUE TITLE
Bonsai times out when opening

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#521]
17 | timed out | Foraging.py | _ConnectBonsai | line 825 | 3C, ephys3

This can probably be resolved by changing the way we open bonsai so that we don't just wait for bonsai to open

**Comment by alexpiet** [comment]
Partial overlap with https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/283

**Comment by ellahiltonvano** [comment]
@alexpiet is this issue still relevant or is this captured by autogenerated issue?

**Comment by alexpiet** [comment]
captured by autogeneration
