### ISSUE TITLE
Move the `scratch` field in nwb to metadata json 

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#527]
As a temporary solution, I previously stored session-related metadata in the `nwb.scratch` field: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/2fea58cc170beb75d6d92e31a9d7253e26c6bf57/src/foraging_gui/TransferToNWB.py#L153-L197

We should relocate all of them to session.json etc.

related issues:
- https://github.com/AllenNeuralDynamics/aind-behavior-blog/discussions/408

@alexpiet @XX-Yin  @Ahad-Allen

**Comment by XX-Yin** [comment]
I have asked Saskia where to store these fields in the session.json. waiting for response

**Comment by hanhou** [comment]
also tagging @hagikent here as he will be working on backfilling metadata json from previously generated nwbs.

**Comment by hanhou** [comment]
> I have asked Saskia where to store these fields in the session.json. waiting for response

My understanding is:

- trials and water info --> https://github.com/AllenNeuralDynamics/aind-data-schema/blob/319bdcb64157f83d242211f1adb843153831c948/src/aind_data_schema/core/session.py#L521-L525
- all other performance-related fields --> `output_parameters`: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/319bdcb64157f83d242211f1adb843153831c948/src/aind_data_schema/core/session.py#L520
- Optogenetics-related --> should go into `stimulus_parameters` of `PhotoStimulation` 

What I'm not sure about:
- Weights-related info --> should go into subject or session?

**Comment by XX-Yin** [comment]
I know they can go to `stimulus_epoch`, but it does not make sense to me. These parameters should be for that session instead of for a specific stimulus (e.g. we have auditory stimulus and optogenetics stimulus, but foraging efficiency, total reward, finish rate ... are for that session instead of for auditory stimulus or optogenetics).

**Comment by alexpiet** [comment]
Resolved by https://github.com/AllenNeuralDynamics/NWB-Packaging-FiberPhotometry-Base-Capsule/pull/30
