### ISSUE TITLE
Warning history

### ISSUE THREAD

**Issue by KanghoonJ** [AllenNeuralDynamics/dynamic-foraging-task#534]
In Foraging GUI, warning message pops up and disappears quickly. Is there a way to keep/see all the warning history?
@XX-Yin @alexpiet

**Comment by XX-Yin** [comment]
@KanghoonJ Do you know when this warning happens (e.g. start, save)? It usually means the warning has been resolved if it disappeared quicky.

**Comment by alexpiet** [comment]
@KanghoonJ You can look at the log to see full details.

If you set `"show_log_info_in_console":true` in `ForagingSettings.json`, then the full log gets dumped to the console window in real time and you can monitor everything

**Comment by KanghoonJ** [comment]
> @KanghoonJ Do you know when this warning happens (e.g. start, save)? It usually means the warning has been resolved if it disappeared quicky.

This warning happens when perseverant behavior occurs and four trials are added to both sides. But the warning message disappears quickly. So it is difficult to retrospectively track when it happened.

**Comment by KanghoonJ** [comment]
> @KanghoonJ You can look at the log to see full details.
> 
> If you set `"show_log_info_in_console":true` in `ForagingSettings.json`, then the full log gets dumped to the console window in real time and you can monitor everything

I see. But with high-speed video recording, especially when logs for recording frames dominates the console window, it's hard to monitor the history of all warning messages. Is there any way to keep the messages in the warning GUI window?

**Comment by alexpiet** [comment]
Lets just cut the number of logs from the high speed video? We did this for photometry, we only record once a second

**Comment by KanghoonJ** [comment]
> Lets just cut the number of logs from the high speed video? We did this for photometry, we only record once a second

Sounds good. @XX-Yin Xinxin, can you cut the number of logs from the high speed videos shown in the console window?

**Comment by XX-Yin** [comment]
> We did this for photometry, we only record once a second

@KanghoonJ This log information for high-speed videos is different from the photometry. The log of photometry is from the OSC, and the log of the high-speed videos is in bonsai. I don't know how to cut the number on the bonsai side.

**Comment by alexpiet** [comment]
@bruno-f-cruz Is there an easy way to filter messages from bonsai? The high speed video frames are coming in at 500Hz (for two cameras) and swamp everything else.

**Comment by XX-Yin** [comment]
@bruno-f-cruz @alexpiet 
Another possibility is to separate the console window for information from the high-speed camera and OSC messages. I am not sure how to do it or if it's possible.

**Comment by bruno-f-cruz** [comment]
> Is there an easy way to filter messages from bonsai?

Not sure what `messages` mean in this context. Filtering of messages should generally be handled by clients (python I guess?) not servers (Bonsai) tho.

> Another possibility is to separate the console window for information from the high-speed camera and OSC messages. I am not sure how to do it or if it's possible.
Not sure what this means either. If you are trying to get two distinct channels of information you could create two pipes, but you are probably better off just using two OSC or ZMQ sockets or/and topics.

**Comment by alexpiet** [comment]
@bruno-f-cruz Bonsai is sending messages/statements to stdout and stderr. Python is redirecting those to our log file. The bonsai statements are each frame of the camera, so they happen at 500Hz. 

Redirection in python happening like this:
```
            process = subprocess.Popen(self.bonsai_path+' '+self.bonsaiworkflow_path+' -p '+'SettingsPath='+self.SettingFolder+'\\'+SettingsBox+ ' --start --no-editor',cwd=CWD,shell=True,
                stdout = subprocess.PIPE, stderr = subprocess.STDOUT,text=True)

        # Log stdout and stderr from bonsai in a separate thread
        threading.Thread(target=log_subprocess_output, args=(process,'BONSAI',)).start()

```

So I could add a filtering step in the `log_subprocess_output` to filter the messages from Bonsai. I was wondering if its possible to make bonsai simply send less messages. For example, only print information about every 500th camera frame

**Comment by alexpiet** [comment]
Notes from in person discussion with @bruno-f-cruz 

1. The output we see in the logs is coming from fmpeg, not bonsai. Bonsai is calling fmpeg, and then piping the output to python. We could possibly add a flag that changes the verbose level of fmpeg
2. We could alternatively log the messages from bonsai into a separate file. This would remove the problem of having verbose messages, but adds the complexity of having two logs
3. We could filter the frequency of messages in python.

**Comment by alexpiet** [comment]
@KanghoonJ @XX-Yin @hagikent 

If you want to stop the high speed camera from flooding the log with each frame trigger, you can open `Settings_box#.csv` and add ` -v 24` to the codec. This tells `ffmpeg` to only output information about errors and warnings. Which greatly cuts down on the amount of stuff in the log. 

I updated the 446 computers. 

I will make a PR to update the settings template
