### ISSUE TITLE
Set the randomness distribution separately for block and ITI/Delay

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#542]
It's better to draw the block length from the uniform distribution and the ITI/delay from the exponential distribution. The current code sets the same randomness distribution for block length and ITI/delay.

**Comment by alexpiet** [comment]
Why set the block length from the uniform distribution?

**Comment by XX-Yin** [comment]
For uncoupled task: Yes
For coupled task: It's truncated exponential distribution.

**Comment by XX-Yin** [comment]
To be more specific. 

For uncoupled task: 
Block: uniform
ITI/Delay: truncated exponential

For coupled task:
Block: truncated exponential
ITI/Delay: truncated exponential

**Comment by ellahiltonvano** [comment]
@XX-Yin is this an update you still think should be implemented?

**Comment by XX-Yin** [comment]
We has a PR that will probably not be merged soon. Please close this issue at this moment.
