### ISSUE TITLE
Flush lines doesn't stay open

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#555]
- Water stops coming out. Check to see how long the valve stays open in the code. 
- @NgD-Huy Notes that sometimes after the water has stopped coming out and then you press "close" then more water comes out!

**Comment by micahwoodard** [comment]
@alexpiet could you point me towards any documentation for how the RigClient works? I've tracked down that [the code](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/e915c47b9cbc3a98d2bbc92ea692de23f724a9c5/src/foraging_gui/rigcontrol.py#L123) that opens the flush lines, but am getting stuck understanding what values correspond to what actions when calling functions within RigControl

**Comment by alexpiet** [comment]
I'm not sure anything is documented. RigClient sends messages (via OSC) to the bonsai workflow. Do you know how to open the bonsai workflow?

@XX-Yin is the bonsai workflow documented anywhere?

**Comment by micahwoodard** [comment]
@XX-Yin Specifically, I'm confused what the value arguments correspond to for some of the RigControl functions. Like here in the code
```
        if self.OpenLeftForever.isChecked():
            # change button color
            self.OpenLeftForever.setStyleSheet("background-color : green;")
            # set the valve open time
            self.MainWindow.Channel.LeftValue(float(1000)*1000) 
            time.sleep(0.01) 
            # open the valve
            self.MainWindow.Channel3.ManualWater_Left(int(1))
```
Is the argument for LeftValue the time it stays open or is it like a mapped value specifying something? If it's the time, what unit is it? Is that something I can find in the bonsai workflow?

**Comment by XX-Yin** [comment]
@micahwoodard The `self.MainWindow.Channel.LeftValue` sends the `valve open time` to the bonsai through OSC message. 

@alexpiet This is a known issue for me. I tried to keep the valve open forever by setting a very large `valve open time`, but it seems that there is a largest valve open time in the harp behavior board. After exceeding the largest valve open time, the valve will be closed automatically.

**Comment by XX-Yin** [comment]
@micahwoodard The unit is `ms`

**Comment by micahwoodard** [comment]
Hmm maybe I can implement a thread logic to keep setting the valve open time to the highest number until the button is clicked to close? That could be a way around this limit. Ella tells me it only stays open for 15-20 seconds. Is this the limit you're seeing too @XX-Yin ?

**Comment by XX-Yin** [comment]
@micahwoodard I think it should work. Set the valve open time to be a little smaller than the maximum open time (e.g. 15s), and reopen the valve after 15s.
