### ISSUE TITLE
High Speed Camera turn on is very slow, should provide faster alert to user that its opening

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#557]
Maybe just the order of operations on changing the `Start` button color

**Comment by alexpiet** [comment]
@XX-Yin When starting and stopping the camera, you have a `time.sleep(5)` command. What is this doing? Can we remove it?

**Comment by XX-Yin** [comment]
Hi @alexpiet, this is related to delay the logging when starting the camera. The logic is `start logging -> delay -> send the camera trigger -> stop camera trigger -> delay -> stop the logging`. The delay is very important for the camera to be ready for receiving triggers.
