### ISSUE TITLE
Redundancy/mis-hierarchi in data saving folder structure

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#56]
In the current config, data are saved into the following 5 subfolders:
SessionFolder/EphysFolder
SessionFolder/HarpFolder
SessionFolder/PhotometryFolder
SessionFolder/TrainingFolder
SessionFolder/VideoFolder

This is great. However, actual `Photometry` and `Video` data are currently saved into 
SessionFolder/HarpFolder/PhotometryFolder
SessionFolder/HarpFolder/VideoFolder

while leaving the following two empty:
SessionFolder/PhotometryFolder
SessionFolder/VideoFolder
____
This is because the GUI code is sending the HarpFolder as the `RootPath` to Bonsai via OSC.
Can @alexpiet @hanhou fix the GUI part? I can take care of fixing the Bonsai part.

I wanted to fix this before working on data streaming to s3. (which likely requires functional metadata anyways beforehand...)

**Comment by alexpiet** [comment]
@hagikent Where do you want the `Photometry` and `Video` data saved? into SessionFolder/PhotometryFolder?

**Comment by alexpiet** [comment]
This issue is a continuation of: https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/49

@XX-Yin Can you clarify what needs to be updated in `MyFunctions._GetLicks()` in order to save the Photometry data in the right folder?

**Comment by XX-Yin** [comment]
I don't think we need to update MyFunctions._GetLicks().

The rootpath sent from the python through OSC message is SessionFolder/HarpFolder/. Then, we concatenate the rootpath with PhotometryFolder or VideoFolder in bonsai. We can solve this by directly connecting the SessionFolder with the PhotometryFolder or VideoFolder in Bonsai.

**Comment by hagikent** [comment]
> @hagikent Where do you want the `Photometry` and `Video` data saved? into SessionFolder/PhotometryFolder?

`Photometry` data to  SessionFolder/PhotometryFolder
`Video` data to SessionFolder/VideoFolder

**Comment by alexpiet** [comment]
Just to be extra clear, is this issue still active now that the fiber photometry workflow has been separated?

**Comment by hagikent** [comment]
Still relevant. Although I haven't implemented yet (because of the quick fix last night), the idea is to receive the same OSC  from GUI (BonsaiOSC:4002) by the photometry-bonsai and to save the data into the same session folder, with the organisation described above.

**Comment by hagikent** [comment]
thanks for catching this old issue; yes, orthogonality solved as a byproduct of #299
