### ISSUE TITLE
Add 446 PCs to the Streamlit pipeline

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#568]
Since 446 PCs are now running, we should add them to the Steramlit pipeline

- [x] Add [new 446 PC names](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/COM-Port-USB-Camera-Table) to Han's [uploading script](https://github.com/AllenNeuralDynamics/aind-foraging-behavior-bonsai-trigger-pipeline/blob/main/code/util_upload_nwb_to_s3/behavior_pipeline_bonsai.py).
     - I assume that the `user_name` and `passcode` are the same as 447 PCs. @ellahiltonvano could you confirm?
- [x] Share `C:\behavior_data` to the network.
     -  ssh to the PC and run `net share behavior_data=C:\behavior_data /grant:svc_aind_behavior,FULL` 
- [ ] Confirm that the new sessions appear in Streamlit.
- [ ] Update the documentation [here](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Computer-Configuration#documentation-for-uncommon-actions).

**Comment by hanhou** [comment]
Our first 446 session looks great! @ellahiltonvano @AllenNeuralDynamics/behavior 

![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/24734299/826f7e05-e303-4af1-abd1-b1b13a52c192)

**Comment by hagikent** [comment]
Circling @ZhixiaoSu in here
