### ISSUE TITLE
Session metadata error – very low success rate

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#569]
Related to those issues on individual errors:
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/490
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/491
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/493

I have been handing/uploading all data acquired between 20240528-yesterday, that should have rig and session metadata, and realized that `session.json` generation failure rate seems very high (86/393 >20%). I think this should be fix with high priority.
@XX-Yin @alexpiet are you two working on this?

As I'm working on back-filling rig+session for old data (2024 early and 2023 late) (see this issue: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/482), I will test if those "failed" session can be easily rescued by similar back-filling operation. 

adding @rachelstephlee , who told me that she is happy to help to be familiar with data structure etc.

**Comment by alexpiet** [comment]
@XX-Yin said he will take care of the session metadata errors.

**Comment by XX-Yin** [comment]
I can make updates.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hagikent** [comment]
@alexpiet @hagikent 
Started working on backfiling `session.json` for session that failed to generate metadata.
Could you point me to example `dialog_metadata_file`? What exactly am I supposed to provide in addition to the main `json_file` to `generate_metadata`?

**Comment by XX-Yin** [comment]
I will be out of office in the remaining days of this week. It’s very straightforward and I can show you next week. I will try to make updates on session metadata on weekends if I am still energetic, otherwise will update it next week.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexpiet** [comment]
The code to generate the metadata is confusing. @XX-Yin should be able to help.

The main code generates the metadata by this call:
`foraging_gui.generate_metadata(Obj=Obj)`

So all of the information should be in that dictionary. Which should have a key `meta_data_dialog`, which gets populated by this call: `self.Metadata_dialog.meta_data`

You can see the fields that should be there by looking for that key in a saved session:
<img width="287" alt="MicrosoftTeams-image156ace6c7de971fb2c822d95534b758ff87c22e684c25052d525b4004fa18031" src="https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/7605170/699cb8f3-53ea-4093-b381-29fb875ec143">

Which is also the fields of the metadata popup window
<img width="296" alt="MicrosoftTeams-image87eedb5fb155b1d3e14a6ec035fee6211b23f19781307baef610ebce6d23d9a4" src="https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/7605170/7bc581c2-cb8f-4768-88ff-fc0698eaee17">

Let me know if you need more help

**Comment by XX-Yin** [comment]
[like]  Xinxin Yin reacted to your message:
________________________________

**Comment by XX-Yin** [comment]
@hagikent 

To backfill the session metadata, you can follow steps below. Please let me know if it works. 

1) fill out the session metadata dialog.
![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/ce35ecde-23a4-4731-9eca-89e33a6bbf8e)
2) save the session metadata dialog by clicking the `save` button in the dialog. The data will be saved to `C:\Users\user_name\Documents\ForagingSettings\metadata_dialog`. 
3) run `generate_metadata`. And you need to provide the `behavior json file`, `dialog_metadata_file` saved in the step 2 and the `output_folder`. One example is shown below:
generate_metadata(json_file=r'Y:\715083\behavior_715083_2024-04-26_17-12-15\behavior\715083_2024-04-26_17-12-15.json', dialog_metadata_file=r'C:\Users\xinxin.yin\Documents\ForagingSettings\metadata_dialog\323_EPHYS3_2024-05-13_12-38-51_metadata_dialog.json', output_folder=r'F:\Test\Metadata')

**Comment by hagikent** [comment]
thanks @XX-Yin 
I'm trying NOT to use the GUI; I need to reduce manual steps.

The number of sessions missing session.json after 240528- is not so much and manually patching one-by-one is likely fine.
However, I need to backfill metadata for data from late2023 and early2024 and I cannot do this manual steps for all of them.

Let me try differently and get back to you if need some help/clarification.

**Comment by XX-Yin** [comment]
> thanks @XX-Yin I'm trying NOT to use the GUI; I need to reduce manual steps.
> 
> The number of sessions missing session.json after 240528- is not so much and manually patching one-by-one is likely fine. However, I need to backfill metadata for data from late2023 and early2024 and I cannot do this manual steps for all of them.
> 
> Let me try differently and get back to you if need some help/clarification.

You don't need to fill out all fields in the session metadata dialog. `Probes`, `Left lick sprout reference positions`, `Stick microscopes`  and `Protocols.io ID` are optional.

**Comment by hagikent** [comment]
I made it work without using the GUI to generate the `metadata_dialog` file.

I sort of agree with @alexpiet saying that this is confusing – information to be ingested into `rig.json` and `sessions.json` are intermingled/spread around in both `dialog.json` and the `main-json (nnnnnn_YYMMDDTTTTTjson)`. And most confusing part to me was that the `main-json` has `Metada_dialog` key; very intertwined. I suppose this is because of 
some historical/development-trajectory reasons but not very straightforward for those who didn't know the history.
Longer-term, this should be refactored by incorporating `AIND-mapper`.

For now, I made a minimal generic dialog.json stab, and a snippet to generate only `session.json`. By this, you only need to feed the `main-json` to produce `sessions.json`, most practical converter function for the backfilling purpose.

Will execute the backfilling process and upload remaining data (2023late, 2024early, session-missing-after20240528) by the end of this week.

**Comment by XX-Yin** [comment]
@hagikent 
Glad to see that you can backfill some old sessions. Can you explain a little more how do you make it? 

I can image you only need to provide fields highlighted below to generate the session metadata, and don't need to care about the ephys part. These fields should be consistent if you don't change the rig metadata, which means you only need to do once. 
![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/726ade07-7608-4d5b-ac6c-2ea7f008e79c)

I understand that the code is a little complex that is determined by the complex nature of session metadata itself. During the design process, modularity was considered as a major requirement. The `behavior json`, `rig metadata`, and `metadata dialog` are largely independent in the code. However, they need share information to generate the session metadata. For example, the `session metadata` requires a lot of fields from the `behavior json`; the `ephys part`, `laser parts`, `daqs` etc of the `session metadata` require `rig metadata` to keep naming consistent; the `metadata dialog` requires the `rig metadata` to parse the `probes` and the `stick microscope`. Their integration is inevitable and necessary to automate the entire process and reduce human intervention. 

However, please keep in mind that you can use the independent class `GenerateMetadata` to flexibly integrate them. The `metadata dialog` is designed to capture fields not directly provided by the `behavior json`. So, you only need to provide `metadata dialog` and `behavior json` to `GenerateMetadata` to generate the session metadata. The `metadata dialog` (if provided) is saved to the `behavior json` (just one dictionary called `meta_data_dialog`), which has multiple advantages. 1) We can visualize these metadata fields when we load a behavior json. 2) `Behavior json` and `metadata dialog` can communicate with each other through a shared data format. 3) If we want to regenerate the `session metadata` when we update the code, we only need the `behavior json` as it contains all information (If we add some fields that are not contained in the behavior json, we need to add this field to the `metadata dialog`). 

Please let me know if you need help to generate the session metadata, or if you find specific parts that are confusing so we can make updates.

**Comment by XX-Yin** [comment]
By the way, my understanding is `AIND-mapper` is more for the `rig metadata` than the `session metadata`. The exact form of `AIND-mapper` is not clear. I've been advocating for standardizing "rig metadata", but it seems challenging (one discussion is here https://github.com/AllenNeuralDynamics/dynamic-foraging-task/discussions/460).

**Comment by hagikent** [comment]
https://github.com/AllenNeuralDynamics/aind-metadata-mapper

No, mapper is for both session and rig.

**Comment by XX-Yin** [comment]
It's a collection from many projects. Not sure if we have a general framework to make session metadata reusable across projects

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hagikent** [comment]
That's not the point... the idea of externalizing the mapper function is to catch up with the evolving metadata scheme versions. Our current metadata generation functions are based on a fixed version that is already old and will soon get very obsolete.

Anyway, backfilling is done. You can close this thread if the session metadata failure problem is solved.

**Comment by XX-Yin** [comment]
How does the mapper handle the version of the schema? Some changes of the schema require change the code for generating session metadata (For example, they changed the folder structure in the schema and the code in the session metadata needed to be changed accordingly).  

Still working on other parts.
