### ISSUE TITLE
Cannot convert input to float: MinOptoInterval, ''

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#572]
10 | Cannot convert input to float: MinOptoInterval, '' | Foraging.py | keyPressEvent | line 1737 | ephys3

@XX-Yin

**Comment by alexpiet** [comment]
This is happening on all rigs now

**Comment by XX-Yin** [comment]
Ok, let me take a look.

**Comment by XX-Yin** [comment]
@alexpiet I can't repeat this issue on my computer.

**Comment by alexpiet** [comment]
It probably happens when `MinOptoInterval` is set to the empty string, and you press enter. It happened 81 times last wed-this morning. On these rigs: 1A, 1B, 1C, 1D, 2A, 2B, 2C, 2D, 3A, 3B, 3C, 3D, 7B, ephys1, ephys3

**Comment by alexpiet** [comment]
Happens on all rigs
80 | Cannot convert input to float: MinOptoInterval, '' | Foraging.py | keyPressEvent | line 1749 | 1A, 1B, 1C, 2A, 2B, 2C, 3C, 3D, 6A, 6B, 6C, 6D, 7A, 7B, 7C, 7D, 8A, 8B, 8C, 8D, ephys1, ephys3

**Comment by XX-Yin** [comment]
I can repeat this issue in the current main branch, but I don't fully understand the reason. This issue was somehow resolved in the develop branch by recent PRs.

**Comment by alexpiet** [comment]
We can close next monday if we dont see the error after this weeks updates
