### ISSUE TITLE
Nested logging issues

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#59]
I found that if line 306 is run, lines 307-309 will not run. Instead, it jumps directly to 311 (shown below). In this case, newscale will not be able to connect. I'm wondering if this has anything to do with multithreading. I temporarily solved it by removing "logging.error(str(e))" in the line 306, which is not a satisfied solution and needs to be figured out. 

Foraging.py
![image](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/109394934/be33a4f0-2183-4f96-8854-576060974754)

**Comment by alexpiet** [comment]
Hmm, ok. Probably can fix with a pass, break, or continue statement.

**Comment by alexpiet** [comment]
Can you clarify what you want this function to do? Why do we have nested try/except blocks to begin with?

**Comment by XX-Yin** [comment]
It's not necessary. And we can reorganize it to avoid nested try/except structure for this specific case. There is this nested structure elsewhere in the code. It's better to find a general solution.

**Comment by alexpiet** [comment]
Closing this issue as its non-specific.
