### ISSUE TITLE
3C newscale stage not connected

### ISSUE THREAD

**Issue by henryloeffler** [AllenNeuralDynamics/dynamic-foraging-task#594]
3C gave a newscale not connected error, and the lick spout did not respond to manipulations from the gui. 
![IMG_4645](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/90724707/c520e9ec-55bb-4eb8-9c4b-6102797e1f0c)

**Comment by alexpiet** [comment]
not fixing any newscale issues
