### ISSUE TITLE
Have GUI write directly to SLIMS

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#607]
- python API that writes to SLIMS is done
- work with @lisayk to implement
- to define:
    - What information needs to get logged? total water? Or split by earned and free water?
    - Any info other than water and mouse id?
    - Does the time/name of the session need to get tracked? 
    - Presumably this logging call should be done once/session, at the end of the session. In this case, if the session crashes, should RAs manually enter water?
    - Or, we could update the water after every trial. This produces 500x calls to SLIMS. Is that bad?

**Comment by macarenasa** [comment]
@alexpiet @hanhou - Can we start defining the requirements of the API that writes from the GUI directly to SLIMS here prior to scheduling a meeting?

**Comment by alexpiet** [comment]
Notes from 07/29/2024 meeting with Lisa/Chris/Bruno/David

Chris M developed an API for fetching/writing session events to SLIMS.

**Comment by macarenasa** [comment]
@alexpiet @hanhou - We need to find a way to have the GUI chat with SLIMS for both behavior session and waterlog (those APIs are available, the starting point from the GUI is not available).

**Comment by alexpiet** [comment]
Here is the logic of what we need:

- [exists] The user enters the ID of the mouse they want to run
- [needed] The GUI queries SLIMS for that mouse, and SLIMS returns the behavior session event for that mouse/day. 
- [needed] The behavior session event contains the task, stage, and parameters.
- [exists] The GUI runs the session with those task/stage/parameters 
- [partial] The session ends, and the GUI determines the recommended next task/stage/parameters
- [exists] The user weights the mouse to determine the final weight
- [needed] The GUI writes the task/stage/parameter recommendation to SLIMS
- [needed] The GUI writes the consumed water, and final weight to waterlog.

**Comment by alexpiet** [comment]
Closing this since we are writing water info to slims
