### ISSUE TITLE
Add a task scheduler to automatically update repo on rig computers

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#61]
- https://learn.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-start-page
- Key step in: https://github.com/AllenNeuralDynamics/aind-behavior-blog/discussions/88
- https://docs.github.com/en/rest/pulls?apiVersion=2022-11-28

1. Create a `.bat` file that pulls from github:
```
cd <directory>
echo get-date -format "yyyy-MM-dd HH:mm:ss" >> <logfile>
echo <repository name> >> <logfile>
git pull origin master >> <logfile> 2>&1
```
2. Save the output from that command to a log file
3. Use Task Scheduler to run the `.bat` file weekly

**Comment by jsiegle** [comment]
Can you add me to the `aind-behavior-blog` repo? I'm not currently able to see it.

**Comment by alexpiet** [comment]
@hanhou Can you add @jsiegle to `aind-behavior-blog`? I either don't have access, or can't find the option on the repo.

**Comment by hanhou** [comment]
I don't have administrator privileges either. @bruno-f-cruz, could you add Josh?
