### ISSUE TITLE
FATAL:AttributeError: 'AutoTrainDialog' object has no attribute 'df_training_manager'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#630]
3	FATAL:AttributeError: 'AutoTrainDialog' object has no attribute 'df_training_manager'	Foraging.py	exception_hook	line 4407	ephys1

**Comment by hanhou** [comment]
@KanghoonJ @alexpiet  Could you point me to the log file where the error occurred?

**Comment by alexpiet** [comment]
[W10DT713669-A_gui_log_2024-07-24_12-36-39.txt](https://github.com/user-attachments/files/16445026/W10DT713669-A_gui_log_2024-07-24_12-36-39.txt)

**Comment by hanhou** [comment]
> 12:37:45 PM:ERROR:aws_util:aws_util.py:import_df_from_s3:line 122:Error reading file from S3: SSL validation failed for https://aind-behavior-data.s3.amazonaws.com/foraging_nwb_bonsai_processed/df_sessions.pkl Cannot connect to host aind-behavior-data.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
12:37:45 PM:ERROR:auto_train_manager:auto_train_manager.py:download_from_database:line 400:No df_behavior found, exiting...
12:37:45 PM:ERROR:Dialogs:Dialogs.py:_connect_auto_training_manager:line 2543:AWS connection failed!

I believe this S3 error was on the AWS side, not ours, and it was also intermittent and rare. I checked a few other log files before and after this session, and the AutoTrain worked fine:

W10DT713669-A_gui_log_2024-07-24_10-37-27.txt
W10DT713669-A_gui_log_2024-07-24_12-41-48.txt
W10DT713669-A_gui_log_2024-07-29_12-17-38.txt
W10DT713669-A_gui_log_2024-07-30_12-20-32.txt

I'll close this issue, but let me know if it happens again @KanghoonJ

**Comment by KanghoonJ** [comment]
> > 12:37:45 PM:ERROR:aws_util:aws_util.py:import_df_from_s3:line 122:Error reading file from S3: SSL validation failed for https://aind-behavior-data.s3.amazonaws.com/foraging_nwb_bonsai_processed/df_sessions.pkl Cannot connect to host aind-behavior-data.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
> > 12:37:45 PM:ERROR:auto_train_manager:auto_train_manager.py:download_from_database:line 400:No df_behavior found, exiting...
> > 12:37:45 PM:ERROR:Dialogs:Dialogs.py:_connect_auto_training_manager:line 2543:AWS connection failed!
> 
> I believe this S3 error was on the AWS side, not ours, and it was also intermittent and rare. I checked a few other log files before and after this session, and the AutoTrain worked fine:
> 
> W10DT713669-A_gui_log_2024-07-24_10-37-27.txt W10DT713669-A_gui_log_2024-07-24_12-41-48.txt W10DT713669-A_gui_log_2024-07-29_12-17-38.txt W10DT713669-A_gui_log_2024-07-30_12-20-32.txt
> 
> I'll close this issue, but let me know if it happens again @KanghoonJ

I used dynamic foraging GUI to generate metadata for ephys only (without behavior training) animals. To generate metadata, I had to create new subject in GUI. My guess is that this metadata generation without behavior training might cause this error message.

**Comment by hanhou** [comment]
I think this should be just a coincidence, because the error message was about AWS certification and cannot be related to any session.
