### ISSUE TITLE
BONSAI: System.IO.IOException: The file '\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#632]
3	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-6-D\708026\behavior_708026_2024-07-19_09-10-57\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	Foraging.py	log_subprocess_output	line 4418	6D
3	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-B\719511\behavior_719511_2024-07-22_09-48-19\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	Foraging.py	log_subprocess_output	line 4418	7B2	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-6-B\711281\behavior_711281_2024-07-24_09-20-09\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	Foraging.py	log_subprocess_output	line 4418	6B
2	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-B\712028\behavior_712028_2024-07-11_10-16-57\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	Foraging.py	log_subprocess_output	line 4418	8B
2	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-B\712028\behavior_712028_2024-07-24_10-00-31\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	Foraging.py	log_subprocess_output	line 4418	8B
2	BONSAI: System.IO.IOException: The file 'C:\behavior_data\447-3-D\711041\behavior_711041_2024-07-24_13-35-46\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	Foraging.py	log_subprocess_output	line 4418	3D
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-6-A\712028\behavior_712028_2024-07-09_19-32-24\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 6A
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-6-C\712028\behavior_712028_2024-07-12_09-34-38\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 6C
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-A\712028\behavior_712028_2024-07-18_09-32-19\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 7A
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-B\711281\behavior_711281_2024-07-17_10-37-06\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 8B
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-B\711281\behavior_711281_2024-07-18_09-36-25\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 7B
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-C\712031\behavior_712031_2024-07-22_09-38-09\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 7C
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-C\714314\behavior_714314_2024-07-18_09-37-59\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 7C
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-D\711281\behavior_711281_2024-07-12_09-25-59\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 7D
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-A\711281\behavior_711281_2024-07-22_09-21-45\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 8A
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-C\717531\behavior_717531_2024-07-22_09-58-11\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 8C
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-D\712028\behavior_712028_2024-07-22_09-46-31\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 8D
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-D\712031\behavior_712031_2024-07-17_10-59-06\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 8D
1 | BONSAI: System.IO.IOException: The file 'C:\behavior_data\447-3-D\711041\behavior_711041_2024-07-23_12-26-39\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists. | Foraging.py | log_subprocess_output | line 4418 | 3D

1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-6-A\712028\behavior_712028_2024-07-09_19-32-24\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	Foraging.py	log_subprocess_output	line 4418	6A
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-6-C\712028\behavior_712028_2024-07-12_09-34-38\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	6C
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-A\712028\behavior_712028_2024-07-18_09-32-19\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	7A
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-B\711281\behavior_711281_2024-07-17_10-37-06\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	8B
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-B\711281\behavior_711281_2024-07-18_09-36-25\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	7B
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-C\712031\behavior_712031_2024-07-22_09-38-09\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	7C
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-C\714314\behavior_714314_2024-07-18_09-37-59\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	7C
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-7-D\711281\behavior_711281_2024-07-12_09-25-59\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	7D
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-A\711281\behavior_711281_2024-07-22_09-21-45\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	8A
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-C\717531\behavior_717531_2024-07-22_09-58-11\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	8C
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-D\712028\behavior_712028_2024-07-22_09-46-31\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	8D
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\446-8-D\712031\behavior_712031_2024-07-17_10-59-06\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	8D
1	BONSAI: System.IO.IOException: The file 'C:\behavior_data\447-3-D\711041\behavior_711041_2024-07-23_12-26-39\behavior\raw.harp/ToBonsaiOSC/loggerstarted.csv' already exists.	[Foraging.py](http://foraging.py/)	log_subprocess_output	line 4418	3D

**Comment by XX-Yin** [comment]
It appears that this only happens in the behavior box, not in the ephys box.
