### ISSUE TITLE
GUI does not alert for saving without closing

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#651]
- Perhaps auto saving messes with this?
- three times yesterday users closed the GUI without saving final weight

**Comment by alexpiet** [comment]
Details:
- Its unclear to me why the GUI doesn't alert for saving without closing. The first step is trying to replicate this

**Comment by micahwoodard** [comment]
- seperate out post wieght info vs unsaved data
- let ra overwrite
