### ISSUE TITLE
Ensure schedule information is set properly

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#653]
- check for FIP on/off, and mode
- check for curriculum
- Good bridge issue before using SLIMS to set all of this information automatically.

**Comment by alexpiet** [comment]
We can address https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/559 at the same time. 
Proposed solution:
- Move the logic that loads the schedule and sets project information from `Foraging._OpenNewMouse` to `Foraging._Start`
- Check if the curriculum matches
- Check if FIP status is correct
- Check if FIP mode is correct
- We dont need to check if its the correct box, trainer, or training time, since those can be flexible. 

When we move to loading this information from SLIMS, we should have the GUI set all of those fields automatically. But for now, lets just verify they are correct

**Comment by micahwoodard** [comment]
@alexpiet for check if FIP on/off should I be checking self.FIP_started? I am unclear about which variable indicates if FIP is on or off

**Comment by alexpiet** [comment]
@micahwoodard Good question. You should check if `self.PhotometryB.currentText()=='on'` This is the GUI toggle button that sets whether to run FIP (FIP = Fiber Photometry, fyi). `FIP_started` tells us whether the FIP process has started already for this session, but we already check that if PhotometryB is "on". Since you are checking the schedule, you dont care if the FIP has started or not, only that the toggle has been set to eventual start.

**Comment by micahwoodard** [comment]
Oh okay I should've thought harder about FIP and photometry. If the schedule is blank in the FIP column, does that mean not photometry?

**Comment by alexpiet** [comment]
Yes, if the schedule is blank, then no photometry
