### ISSUE TITLE
drop of frames in 446 high-speed cameras

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#661]
possible reasons
1) wrong camera settings in the spinview.
2) something to do with the port that the camera is connected to the computer.

**Comment by ellahiltonvano** [comment]
@XX-Yin Is this issue still occurring?

**Comment by ellahiltonvano** [comment]
@XX-Yin it looks like there was a PR for this issue, is this resolved?

**Comment by ellahiltonvano** [comment]
@XX-Yin could you please update this issue?

**Comment by XX-Yin** [comment]
> @XX-Yin could you please update this issue?

 I don't follow up this issue. Could somebody confirm the issue of drop of frame?

**Comment by XX-Yin** [comment]
It has been resolved on my rig
