### ISSUE TITLE
Figure out how to flexibly trigger a different pipeline

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#678]
Right now, when creating the upload manifest, all sessions get routed to the same code ocean pipeline. That pipeline works for both pure behavior, and behavior + FIP data. However we should have the flexibility to trigger a different pipeline for scientists doing neural recordings. 

One solution:
- Add a field in ForagingSettings.json that is the name of the pipeline to trigger. This solution would mean that all sessions from the same rig are sent to the same pipeline. This works for the use case at hand (@smrithi-sunil's optical imaging rig 9D).

**Comment by hanhou** [comment]
Could you describe what you have in mind for the final form of the pipelines? For example, will you allow an uploaded asset to trigger different pipelines at the same time? Will you have separate pipelines for each combination of modalities, such as behavior only, behavior + FIP, behavior + ephys, and behavior + FIP + ephys?

I would prefer not to specify a downstream pipeline at the behavior capture stage. Instead, all uploaded sessions trigger the same pipeline, which, based on the available modalities, triggers pre-processing and first-order analysis, and writes to a database. Different projects can then query the database to retrieve intermediate results for project-specific analysis.

**Comment by alexpiet** [comment]
I'm just not sure how we want to handle pre-processing different data modalities. 

My thinking was that we trigger a different pipeline based on modality. Each pipeline would reuse some capsules, like making the NWB file for the behavior data. I admit I hadn't considered behavior+FIP+ephys. I'm also generally assuming the ephys team is doing their own pipeline. 

We could alternatively have one pipeline that splits sessions based on modality, or has lots of capsules that check for the existence of some data modality and then skip the session if its not available.

I don't know Code Ocean well enough to have an opinion about what is easiest or best long term. Open to whatever suggestion makes sense

**Comment by jeromelecoq** [comment]
The current favored approach is to have a list of capsule associated with each modality and trigger them upon upload depending on which modality was collected. 
We will eventually need merging capsule to combine NWB files.

**Comment by alexpiet** [comment]
This question is resolved, closing the issue
