### ISSUE TITLE
Wrong project name when the mouse is not in the schedule

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#770]
Related to update from https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/694

When the animal ID is not in the schedule, the project information will be forced to set as default. This is problematic. When the animal is training in the ephys rig without the schedule information, the project will also be set to default after clicking start (usually we'd like to use a different project information). Please cancel the force default setting.

**Comment by XX-Yin** [comment]
Or make the `default` optional so that we can disable the default settings in the ephys rig

**Comment by alexpiet** [comment]
- Adding a parameters in `ForagingSettings.json` that disables auto filling the project name seems like a good solution. 
- Or changing the logic so that the default doesn't get set if the project name has already been manually configured.

**Comment by XX-Yin** [comment]
The second solution seems to be more universal.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
