### ISSUE TITLE
sessions have mislabeled metadata on modalities

### ISSUE THREAD

**Issue by rachelstephlee** [AllenNeuralDynamics/dynamic-foraging-task#793]
The metadata on modalities (which is used to query for sessions on mongoDB) isn't always correct. 

Per @alexpiet , the modality `fib` is generated automatically if there is a `fiber_photometry_start_time` variable in the main GUI window. This makes sense since the sessions that have the wrong metadata are trained in 447 but finish in the EPHYS rig afterwards. 

The bug may also be in `src/foraging_gui/GenerateMetadata.py`

The fix should be done when the data is generated. we need to make sure that a fiber folder is created to have the `fib` modality. 

Examples of this include: 717263, 714116. 

Fib modality listed here: 
![Image](https://github.com/user-attachments/assets/4c3f4b4e-230d-4116-8cb8-b1d88c0adb29)

But data doesn't have fiber photometry data

![Image](https://github.com/user-attachments/assets/34982d98-24e8-47f4-a01f-9ed99c310a34)

On streamlit we see that it's finished trained on the 323 ephys rig 
![Image](https://github.com/user-attachments/assets/0097dba9-212d-4799-8900-6aee63c833d7)

**Comment by alexpiet** [comment]
I've found the problem. Our data_description.json files are correctly only including "fib" modality, but the upload manifests are listing "fib" as a modality. Some time during the upload process the upload manifest information overwrites the data_description.json.
 
Example
- data_description.json for behavior_753124_2024-10-18_09-39-25 on the acquisition computer only lists behavior as the modality. 
- data_description.json on code ocean, include behavior videos and fib (https://codeocean.allenneuraldynamics.org/data-assets/99c7890b-ddb8-4883-90e4-416b7be2e30b/behavior_753124_2024-10-18_09-39-25_processed_2024-10-19_03-56-01/data_description.json?fullScreen=true&hideDetails=true)

**Comment by alexpiet** [comment]
Solution:
- [ ] Update the upload manifests to only list "fib" and "behavior-videos" if they are actually recorded in the session.
