### ISSUE TITLE
Either update data_description.json, or let the transfer service generate it for us

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#804]
Right now we are making a data_description.json and then uploading it. We can also not make one, and let the transfer service generate it for us. 

If we want to update the data_description.json
@dyf wrote on teams:
> if you want to continue making the data description on the rig, if you aren't already I suggest you fetch funding information from http://aind-metadata-service/ rather than hard-code it. e.g. http://aind-metadata-service/funding/Behavior%20Platform

If we want to let the transfer service generate it for us:
> The other thing we could do is pass modalities and project name to the DTS and it will take care of it for you.

This means making sure the upload manifest contains the accurate modalities in session.json rather, and project_name

**Comment by alexpiet** [comment]
Not urgent. But it would be good to stop hard coding things

**Comment by micahwoodard** [comment]
@alexpiet Is there a flag or button in the code that says if video is being recorded? I'm having trouble finding it

**Comment by micahwoodard** [comment]
> This means making sure the upload manifest contains the accurate modalities in session.json rather, and project_name

Wait maybe I'm confused in what I'm doing. Do I need to use the session.json to populate the upload_manifest modalities and project name? Do I need to remove any  hardcoded funding information from anywhere or what that only used in the data_description file?

**Comment by micahwoodard** [comment]
- I can pull modalities from session.json and then update project name
