### ISSUE TITLE
Could not log git branch and hash: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 3221225786.

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#840]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: log_git_hash<br>line 4686<br>logfile: W10DT714670/W10DT714670-A_gui_log_2024-10-24_10-07-54.txt<br>boxes: ephys4<br>count: 1<br>text: Could not log git branch and hash: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 3221225786.<br><br><br>Log context<br>

```
10:07:54 AM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4662:Starting logfile!
10:07:54 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4673:Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC v.1938 64 bit (AMD64)]
10:07:54 AM:ERROR:Foraging:Foraging.py:log_git_hash:line 4686:Could not log git branch and hash: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 3221225786.
```

**Comment by alexpiet** [comment]
@KanghoonJ What version of `git` is installed on your computer? The non-zero exist status means something crashed while git was running.

**Comment by ellahiltonvano** [comment]
> month old
