### ISSUE TITLE
Request: move light switch in 446 boxes higher, or below water reservoir

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#845]
@NgD-Huy pointed out that removing the water reservoir in the lower boxes is difficult because there is little clearance between the reservoir at the light switches. Moving the light switches a few cm up, or moving them completely below the reservoir would resolve this issue.

**Comment by ellahiltonvano** [comment]
Heston will likely be moving the water reservoirs this coming week, @NgD-Huy I will request adjust the light switches as well.

**Comment by ellahiltonvano** [comment]
Moving the water reservoirs up in 446 has solved the issue, it likely will in 447 as well.

**Comment by ellahiltonvano** [comment]
This is resolved.
