### ISSUE TITLE
Make GUI work without slims credentials

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#868]

**Comment by ellahiltonvano** [comment]
@XX-Yin is this an issue you would like to provide more context for or should we close?

**Comment by XX-Yin** [comment]
@ellahiltonvano The slims credential is required for the current GUI to run. We can make it optional, which helps run GUI in computers without the credential. I can handle this issue

**Comment by ellahiltonvano** [comment]
Great, thanks @XX-Yin!

**Comment by XX-Yin** [comment]
@alexpiet I got this. Currently, I can't run the GUI on my own computer.

**Comment by XX-Yin** [comment]
The idea is to be able to run the GUI with minimal setup.

**Comment by ellahiltonvano** [comment]
@XX-Yin are you able to run your GUI normally now? If so I will close the issue.

**Comment by XX-Yin** [comment]
Not on my own computer.

**Comment by alexpiet** [comment]
Adding the SLIMS credentials takes <5 minutes

**Comment by XX-Yin** [comment]
I can first install the credentials to make the GUI running. Do we have a document about adding the SLIMS credentials?

**Comment by alexpiet** [comment]
I messaged you on teams with the credentials

**Comment by ellahiltonvano** [comment]
@XX-Yin after you have added credentials on your computer please close this issue
