### ISSUE TITLE
Plot Setting Back in gui

### ISSUE THREAD

**Issue by micahwoodard** [AllenNeuralDynamics/dynamic-foraging-task#871]
I previously merged [this branch ](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/784) to get rid of the plot settings widget. It seems like in the develop branch [they are back](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/14af7644fd0e0e41992f7a86e629fbb9388e6354/src/foraging_gui/ForagingGUI.ui#L1845C23-L1845C54)? @alexpiet was this added back in purposefully?

**Comment by alexpiet** [comment]
Not intentional on my part!

**Comment by micahwoodard** [comment]
Upon investigation I think when Jessy merged in the [stage widget pr](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/846/commits/88ee7436696feb2e552427aba7016b6008365dcd) , it was added back in. I'll remove it again

**Comment by alexpiet** [comment]
Its really hard to catch changes to the UI, since the files are so big. For a while we were requiring screenshots of the UI whenever the ui file changes, which helped catch mistakes like this

**Comment by micahwoodard** [comment]
I think what happened is that we approved the pull request when there were merge conflicts. When Jessy fixed these conflicts, he added the plot settings back in and merged with out rereview. We can also make it standard to not approve while there are merge conflicts along with screenshots
