### ISSUE TITLE
visualization bug

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#877]
@micahwoodard @alexpiet 
The RunLength was set to a fixed value, which caused the update of the figure is not smooth. This variable is set and changed in the GUI. 

Left is the current code, and the right is my previous code. Please make it set by GUI instead of hardcoded!

![image](https://github.com/user-attachments/assets/ceeee64e-b0aa-4121-a425-1af3ce447804)
![image](https://github.com/user-attachments/assets/a31d8238-eadd-4375-bd1b-9bdb25dc0908)
![image](https://github.com/user-attachments/assets/012f7802-007c-4ad7-bc78-a1efabae3453)

**Comment by XX-Yin** [comment]
The code review process should be more rigorous. I spent several hours debugging this week.

**Comment by micahwoodard** [comment]
@XX-Yin there was an issue to [remove the plot settings](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/445) widget from the UI. I wrongly hardcoded the kernel_size to 2 because of this. Some widgets referenced in the fix no longer exist, but I will push a fix and request review

**Comment by micahwoodard** [comment]
Looking closer at the code, removing the plot settings would make this value hardcoded. Would it be better to hardcode this value to 10? Also I realize that the plot settings were not removed from the ephys gui. I couldn't find the plot settings group widget so I thought they did not exist. Do you regularly use these widgets?

**Comment by alexpiet** [comment]
@XX-Yin We purposefully removed the plotting settings as part of our on-going efforts to streamline the GUI. Do you use this? What is your use case for changing the plot?

**Comment by alexpiet** [comment]
Can you tell me why you want to change the plot resolution on the GUI? What is the use case for that feature?

**Comment by XX-Yin** [comment]
The answer is in the following question:

Why do you hardcode the runlength to 2 or 10? Which one is better?

**Comment by ellahiltonvano** [comment]
@XX-Yin following back up on this issue

**Comment by XX-Yin** [comment]
@ellahiltonvano We still hardcode the runlength, which is ok. We can close this issue.
