### ISSUE TITLE
GUI Metadata generarion function needs update

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#929]
I'm working on metadata backfill for the old dataset with @rachelstephlee , and we got several pushback from @saskiad , who asks to address "minimal requests". While addressing this, I realized that the up-to-date `rig.json` and `sessions.json` are not meeting her requirement either, and thus, GUI metadata generation function needs to be updated too.

@hagikent and @rachelstephlee will keep addressing back-fill under FIP-Kanban.
Could @alexpiet and @XX-Yin can work on the generation function (or find delegates)?
____
Rig:
1.  "_The solenoids and lick detectors need to be listed as channels_"

Session:
1. "_Lick Sensor Left and Lick Sensor Right are not daq_names_"

         "daq_names": [
            "Harp Behavior",
            "Harp Sound",
            "Harp clock synchronization board",
            "Harp sound amplifier",
            "Lick Sensor Left",
            "Lick Sensor Right"
         ]

2. "_You need reward delivery - which spouts are active and what solution is being provided._"
        
        "reward_delivery": null

3. "_software and script info should be in the stimulus epoch._"
```
         "stimulus_epochs": [
            {
               "stimulus_start_time": "2024-10-24T12:22:59.167803-07:00",
               "stimulus_end_time": "2024-10-24T13:38:00.434420-07:00",
               "stimulus_name": "auditory go cue",
               "session_number": null,
               "software": [],
```

_________
@saskiad
Could you please elaborate on what/how we should fix more concretely?
I guess Sesson#3 should be just adding "Bonsai" but I'm not 100% sure for other requests.

**Comment by alexpiet** [comment]
Those issues are already documented: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/510

**Comment by hagikent** [comment]
@alexpiet thanks! Amendment for `session` seems to be already covered by https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/510 but not the one for `rig`? (I although not sure what channels mean, though)

**Comment by hagikent** [comment]
metadata fix is almost done. still need to wait for saskia to provide explicit instructions on a few vague requests but they are minor.

most folders that miss json files are either:
1.empty (test or duplicated sessions on the same day)
2.screening (no behavior but just checking the signal)
3.too old (before implementing session.json generation function)

**Comment by hagikent** [comment]
Just got feedback from Saskia.

1. The solenoid and lick detectors are connected to a daq, correct? So they need to be listed in the channels field of the daq device they are connected to. https://github.com/AllenNeuralDynamics/aind-data-schema/blob/dev/examples/fip_ophys_rig.py#L251

2. If you have daqs that are "Lick Sensor Left" and "Lick Sensor Right" they must to be listed as daq devices in your rig. This is the problem. Any device in your session MUST be in the rig, with the exact same name. If you are using them, they need to be there. But they need to be there consistently. If these aren't daqs, but are things connected to daqs, then they shouldn't be listed as daq devices in the session.
