### ISSUE TITLE
Saving manual reward time to .json

### ISSUE THREAD

**Issue by ZhixiaoSu** [AllenNeuralDynamics/dynamic-foraging-task#930]
Manual reward time is saved in session.json file but does not seem to be the within the same timescale. 
Example data: 3adf08e6-1805-4dad-9318-d7d77a3bd11b
Time for manual rewards: 
![image](https://github.com/user-attachments/assets/033d4c5f-a378-4441-bc02-22e016d07225)

Time for the session:
![image](https://github.com/user-attachments/assets/7b246268-632f-4724-9e99-8bb6c281dc7d)

Are they aligned to different time points? Would it be better to have them on the same timescale?

**Comment by alexpiet** [comment]
@ZhixiaoSu I think "manual water left time" refers to the valve open time, not the delivery time

**Comment by ZhixiaoSu** [comment]
Oh, that explains it. Do we know where manual reward time is saved then?

**Comment by XX-Yin** [comment]
@ZhixiaoSu 

They are stored in `B_ManualLeftWaterStartTime` and `B_ManualRightWaterStartTime`. They are not the harp timestamp, but they are very close to the harp timestamps (stored in `B_LeftRewardDeliveryTimeHarp` and `B_RightRewardDeliveryTimeHarp`). So, you can find the nearest harp timestamp to get what you want.

**Comment by ZhixiaoSu** [comment]
Thank you so much! I'll go try.

**Comment by ZhixiaoSu** [comment]
I'm able to get manual reward information. Closing the issue.
