### ISSUE TITLE
Get AIND stage controller and record

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#948]
We do this for the newscale stage, but not the AIND stage controller.

**Comment by micahwoodard** [comment]
@alexpiet I remember talking about this but not the exact details. Could you add a bit more details to the issue?

**Comment by alexpiet** [comment]
Sure @micahwoodard 
We want to track the current position of the lickspout stage on every trial for analysis later. For the newscale stages, that is done via the function `Foraging.py/_GetPositions()`. We want to modify that function to work for the AIND stages.

**Comment by micahwoodard** [comment]
> We want to track the current position of the lickspout stage on every trial for analysis later.

@alexpiet I'm a bit confused again about what this ticket is for. Do we want to track stage positions for ever trial or do we want to save the position of the stage at the beginning of a session so ra's can use this reference later? Or both?

**Comment by micahwoodard** [comment]
@alexpiet or @XX-Yin could you point me to where in the code the stage position is being recorded for every trial? I've looked where _GetPositions and _UpdatePosition are being called, but I'm missing where this currently happens during a session.

**Comment by alexpiet** [comment]
@micahwoodard I believe this happens in `MyFunctions.py/_GenerateATrial()` which calls "_GetTrainingParameters()"

**Comment by micahwoodard** [comment]
@alexpiet would it break the post processing pipeline to rename  B_NewscalePositions to B_StagePositions and then make it a dictionary instead of a list? That way we could handle the newscale have x,y,z coords and aind having x, y0, y1, z coords. Or should we assume that the aind stage always has the same value for y0 and y1?

**Comment by alexpiet** [comment]
- We should not assume that y0 and y1 are the same. 
- Good idea to change to a dictionary, it will be easy to update the processing pipeline.
- Just to be verbose, you are proposing:
   - If the session has Newscale stages, then `B_StagePositions` is a dictionary with keys:
      - `x`
      - `y`
      - `z`
   - If the session has AIND stages, then `B_StagePositions` is a dictionary with keys:
      - `x`
      - `y0`
      - `y1`
      - `z`

**Comment by micahwoodard** [comment]
Just a note, Jessy defines the directions as  x, y1, y2, z so I will follow that convention as well

**Comment by XX-Yin** [comment]
The position is stored here:
![image](https://github.com/user-attachments/assets/04c396d5-7583-4d5b-aed6-b8cfbe89d55d)
