### ISSUE TITLE
low priority - auto-generated

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#949]
I saw a lot of issues labeled as "low priority - auto-generated". 

How is "low priority - auto-generated" issue produced? Is it based on automatic tracking of error information from the GUI log file? If so, there are a lot issues that are redundant and nonsense (e.g. due to testing).

**Comment by alexpiet** [comment]
Yes, low priority - auto-generated is given to any error in the GUI logs that wasn't fatal, hasn't so far reoccured.

**Comment by XX-Yin** [comment]
These seem like similar issues?

![image](https://github.com/user-attachments/assets/073aa2ea-f0f4-40f3-a821-928c473bcaba)

**Comment by alexpiet** [comment]
Yes they are. The error generation code isn't smart enough to know to combine them

**Comment by ellahiltonvano** [comment]
I am going to close this issue. @XX-Yin I am tracking these autogenerated for now and will make sure to close as we solve the issues!
